// mail-react/src/views/my-mailbox/index.tsx
import { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Icon } from '@iconify/react';
import { toast } from 'sonner';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  accountDelete,
  accountList,
  accountSetName,
  type AccountListItem,
  type AccountPerm,
} from '@/request/account';
import { hasPerm } from '@/perm';
import { useAccountStore } from '@/store/account';
import AccountMemberDialog from '@/components/account-member-dialog';

const permLabelKey = (p: AccountPerm | undefined | null): 'mailboxOwner' | 'roleAdmin' | 'roleSender' | 'roleViewer' | null => {
  if (p === 'owner') return 'mailboxOwner';
  if (p === 'admin') return 'roleAdmin';
  if (p === 'sender') return 'roleSender';
  if (p === 'viewer') return 'roleViewer';
  return null;
};

export default function MyMailboxView() {
  const { t } = useTranslation();
  const setCurrentAccount = useAccountStore((s) => s.setCurrentAccount);
  const setCurrentAccountId = useAccountStore((s) => s.setCurrentAccountId);

  const [rows, setRows] = useState<AccountListItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [renameTarget, setRenameTarget] = useState<AccountListItem | null>(null);
  const [renameValue, setRenameValue] = useState('');
  const [deleteTarget, setDeleteTarget] = useState<AccountListItem | null>(null);
  const [memberTarget, setMemberTarget] = useState<AccountListItem | null>(null);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const list = await accountList(0, 30);
      setRows(list || []);
    } catch {
      /* interceptor */
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  async function submitRename() {
    if (!renameTarget) return;
    try {
      await accountSetName(renameTarget.accountId, renameValue);
      toast.success(t('setSuccess'));
      setRenameTarget(null);
      refresh();
    } catch {
      /* interceptor */
    }
  }

  async function confirmDelete() {
    if (!deleteTarget) return;
    try {
      await accountDelete(deleteTarget.accountId);
      toast.success(t('setSuccess'));
      setDeleteTarget(null);
      refresh();
    } catch {
      /* interceptor */
    }
  }

  function switchTo(item: AccountListItem) {
    setCurrentAccount(item);
    setCurrentAccountId(item.accountId);
  }

  const canManage = (item: AccountListItem) =>
    item.perm === 'owner' || item.perm === 'admin';

  return (
    <div className="page">
      <div className="page-header">
        <h1>{t('myMailboxes')}</h1>
      </div>
      <div className="page-body">
        <div className="rounded-lg border border-border bg-card">
          <table className="w-full text-sm">
            <thead className="bg-muted text-muted-foreground">
              <tr className="text-left">
                <th className="px-3 py-2 text-caption font-medium">Email</th>
                <th className="px-3 py-2 text-caption font-medium">Name</th>
                <th className="px-3 py-2 text-caption font-medium">{t('mailboxRole')}</th>
                <th className="px-3 py-2 text-caption font-medium">{t('mailboxOwner')}</th>
                <th className="px-3 py-2 text-caption font-medium text-right">{t('memberCount')}</th>
                <th className="px-3 py-2 text-caption font-medium"></th>
              </tr>
            </thead>
            <tbody>
              {rows.map((item) => (
                <tr key={item.accountId} className="border-t">
                  <td className="px-3 py-2 font-mono text-num">{item.email}</td>
                  <td className="px-3 py-2">{item.name || '—'}</td>
                  <td className="px-3 py-2">
                    {permLabelKey(item.perm) ? (
                      <Badge variant={item.perm === 'owner' ? 'default' : 'secondary'}>
                        {t(permLabelKey(item.perm) as 'mailboxOwner')}
                      </Badge>
                    ) : (
                      '—'
                    )}
                  </td>
                  <td className="px-3 py-2 font-mono text-num text-muted-foreground">
                    {item.ownerEmail || '—'}
                  </td>
                  <td className="px-3 py-2 text-right font-mono text-num">
                    {item.perm === 'owner' ? (item.memberCount ?? 0) : '—'}
                  </td>
                  <td className="px-3 py-2 text-right">
                    <div className="inline-flex items-center gap-2">
                      <Icon
                        icon="ion:swap-horizontal"
                        width="16"
                        height="16"
                        className="cursor-pointer text-muted-foreground hover:text-foreground"
                        onClick={() => switchTo(item)}
                      />
                      {canManage(item) && (
                        <Icon
                          icon="ion:people-outline"
                          width="16"
                          height="16"
                          className="cursor-pointer text-muted-foreground hover:text-foreground"
                          onClick={() => setMemberTarget(item)}
                        />
                      )}
                      {canManage(item) && (
                        <Icon
                          icon="ion:create-outline"
                          width="16"
                          height="16"
                          className="cursor-pointer text-muted-foreground hover:text-foreground"
                          onClick={() => {
                            setRenameTarget(item);
                            setRenameValue(item.name ?? '');
                          }}
                        />
                      )}
                      {item.perm === 'owner' && item.accountId !== useAccountStore.getState().currentAccountId && hasPerm('account:delete') && (
                        <Icon
                          icon="ion:trash-outline"
                          width="16"
                          height="16"
                          className="cursor-pointer text-muted-foreground hover:text-destructive"
                          onClick={() => setDeleteTarget(item)}
                        />
                      )}
                    </div>
                  </td>
                </tr>
              ))}
              {!loading && rows.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-3 py-6 text-center text-muted-foreground">
                    —
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <Dialog open={!!renameTarget} onOpenChange={(o) => !o && setRenameTarget(null)}>
        <DialogContent className="max-w-[420px]">
          <DialogHeader>
            <DialogTitle>{t('rename')}</DialogTitle>
          </DialogHeader>
          <Input
            value={renameValue}
            onChange={(e) => setRenameValue(e.target.value)}
            maxLength={30}
          />
          <DialogFooter>
            <Button variant="outline" onClick={() => setRenameTarget(null)}>
              {t('cancel')}
            </Button>
            <Button onClick={submitRename}>{t('confirm')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <AlertDialog open={!!deleteTarget} onOpenChange={(o) => !o && setDeleteTarget(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('delete')}</AlertDialogTitle>
            <AlertDialogDescription>{deleteTarget?.email}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t('cancel')}</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete}>{t('confirm')}</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {memberTarget && (
        <AccountMemberDialog
          open={!!memberTarget}
          accountId={memberTarget.accountId}
          accountEmail={memberTarget.email}
          canManage={canManage(memberTarget)}
          onClose={() => setMemberTarget(null)}
        />
      )}
    </div>
  );
}

// mail-vue/src/views/my-mailbox/index.vue
<template>
  <div class="box">
    <div class="title">{{ $t('myMailboxes') }}</div>
    <div class="subtitle">{{ $t('sharedWithMe') }}</div>
    <el-table :data="rows" v-loading="loading" class="table" :empty-text="loading ? '' : '—'">
      <el-table-column :label="'Email'" :min-width="220">
        <template #default="props">
          <span class="email-cell">{{ props.row.email }}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('rename')" :width="120">
        <template #default="props">
          <span>{{ props.row.name || '—' }}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('mailboxRole')" :width="120">
        <template #default="props">
          <el-tag v-if="props.row.perm === 'owner'" type="primary" disable-transitions>
            {{ $t('mailboxOwner') }}
          </el-tag>
          <el-tag v-else-if="props.row.perm === 'admin'" disable-transitions>
            {{ $t('roleAdmin') }}
          </el-tag>
          <el-tag v-else-if="props.row.perm === 'sender'" type="info" disable-transitions>
            {{ $t('roleSender') }}
          </el-tag>
          <el-tag v-else-if="props.row.perm === 'viewer'" type="info" disable-transitions>
            {{ $t('roleViewer') }}
          </el-tag>
          <span v-else>—</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('mailboxOwner')" :min-width="200">
        <template #default="props">
          <span class="email-cell" style="color: var(--regular-text-color);">
            {{ props.row.ownerEmail || '—' }}
          </span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('memberCount')" :width="90" align="right">
        <template #default="props">
          <span class="num">
            {{ props.row.perm === 'owner' ? (props.row.memberCount ?? 0) : '—' }}
          </span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('action')" :width="120" align="right">
        <template #default="props">
          <div class="row-actions">
            <Icon
                icon="ion:swap-horizontal"
                width="18"
                height="18"
                class="row-icon"
                @click="switchTo(props.row)"
            />
            <Icon
                v-if="canManage(props.row)"
                icon="ion:people-outline"
                width="18"
                height="18"
                class="row-icon"
                @click="openMember(props.row)"
            />
            <Icon
                v-if="canManage(props.row)"
                icon="ion:create-outline"
                width="18"
                height="18"
                class="row-icon"
                @click="renameMailbox(props.row)"
            />
            <Icon
                v-if="props.row.perm === 'owner' && props.row.accountId !== selfAccountId && hasPerm('account:delete')"
                icon="ion:trash-outline"
                width="18"
                height="18"
                class="row-icon row-icon-danger"
                @click="deleteMailbox(props.row)"
            />
          </div>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog v-model="renameShow" :title="$t('rename')" width="420">
      <el-input v-model="renameValue" :maxlength="30"/>
      <template #footer>
        <el-button @click="renameShow = false">{{ $t('cancel') }}</el-button>
        <el-button type="primary" @click="submitRename">{{ $t('confirm') }}</el-button>
      </template>
    </el-dialog>

    <AccountMemberDialog
        v-if="memberTarget"
        :open="!!memberTarget"
        :account-id="memberTarget.accountId"
        :account-email="memberTarget.email"
        :can-manage="canManage(memberTarget)"
        @close="memberTarget = null"
    />
  </div>
</template>

<script setup>
import {defineOptions, ref, onMounted, computed} from 'vue'
import {Icon} from '@iconify/vue'
import {useI18n} from 'vue-i18n'
import {
  accountDelete,
  accountList,
  accountSetName,
} from '@/request/account.js'
import {useAccountStore} from '@/store/account.js'
import {useUserStore} from '@/store/user.js'
import {hasPerm} from '@/perm/perm.js'
import AccountMemberDialog from '@/components/account-member-dialog.vue'

defineOptions({name: 'myMailbox'})

const {t} = useI18n()
const accountStore = useAccountStore()
const userStore = useUserStore()

const rows = ref([])
const loading = ref(false)

const memberTarget = ref(null)
const renameShow = ref(false)
const renameTarget = ref(null)
const renameValue = ref('')

const selfAccountId = computed(() => userStore.user?.account?.accountId)

const canManage = (item) => item.perm === 'owner' || item.perm === 'admin'

async function refresh() {
  loading.value = true
  try {
    const list = await accountList(0, 30)
    rows.value = list || []
  } catch (e) {
    rows.value = []
  } finally {
    loading.value = false
  }
}

onMounted(refresh)

function switchTo(item) {
  accountStore.currentAccountId = item.accountId
  accountStore.currentAccount = item
}

function openMember(item) {
  memberTarget.value = item
}

function renameMailbox(item) {
  renameTarget.value = item
  renameValue.value = item.name ?? ''
  renameShow.value = true
}

async function submitRename() {
  if (!renameTarget.value) return
  await accountSetName(renameTarget.value.accountId, renameValue.value)
  ElMessage({message: t('setSuccess'), type: 'success', plain: true})
  renameShow.value = false
  refresh()
}

function deleteMailbox(item) {
  ElMessageBox.confirm(t('delConfirm', {msg: item.email}), {
    confirmButtonText: t('confirm'),
    cancelButtonText: t('cancel'),
    type: 'warning',
  }).then(async () => {
    await accountDelete(item.accountId)
    ElMessage({message: t('delSuccessMsg'), type: 'success', plain: true})
    refresh()
  })
}
</script>

<style scoped lang="scss">
.box {
  padding: 30px 40px;

  .title {
    font-size: 18px;
    font-weight: bold;
  }

  .subtitle {
    color: var(--regular-text-color);
    font-size: 12px;
    margin-top: 4px;
    margin-bottom: 18px;
  }

  .table {
    width: 100%;

    .email-cell {
      font-family: var(--el-font-family-monospace, monospace);
    }

    .num {
      font-family: var(--el-font-family-monospace, monospace);
    }

    :deep(.cell) {
      word-break: break-all;
    }
  }

  .row-actions {
    display: inline-flex;
    align-items: center;
    gap: 10px;
  }

  .row-icon {
    cursor: pointer;
    color: var(--regular-text-color);
    transition: color 200ms;

    &:hover {
      color: var(--el-color-primary);
    }
  }

  .row-icon-danger:hover {
    color: var(--el-color-danger);
  }
}
</style>
