// mail-react/src/views/star/index.tsx
import { useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import EmailScroll, { type EmailScrollHandle } from '@/components/email-scroll';
import { emailDelete as emailDeleteFn } from '@/request/email';
import {
  starAdd as starAddFn,
  starCancel as starCancelFn,
  starList,
} from '@/request/star';
import { useEmailStore } from '@/store/email';

export default function StarView() {
  const navigate = useNavigate();
  const emailStore = useEmailStore();
  const scrollRef = useRef<EmailScrollHandle>(null);

  useEffect(() => {
    emailStore.setStarScroll(scrollRef.current);
    return () => {
      emailStore.setStarScroll(null);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function jumpContent(email: any) {
    emailStore.setContentData({
      email,
      delType: 'logic',
      showStar: true,
      showReply: true,
    });
    navigate('/message');
  }

  function cancelStar(email: any) {
    useEmailStore.setState({ cancelStarEmailId: email.emailId });
    scrollRef.current?.deleteEmail([email.emailId]);
  }

  async function getEmailList(emailId: number, size: number) {
    const data = await starList(emailId, size);
    if (data.latestEmail) {
      data.latestEmail.reqAccountId = useEmailStore.getState().starScroll ? 0 : 0;
    }
    return { list: data.list, total: data.list.length, latestEmail: data.latestEmail };
  }

  return (
    <EmailScroll
      ref={scrollRef}
      allowStar={false}
      cancelSuccess={cancelStar}
      getEmailList={getEmailList}
      emailDelete={emailDeleteFn}
      starAdd={starAddFn}
      starCancel={starCancelFn}
      onJump={jumpContent}
      actionLeft="6px"
      showAccountIcon={false}
      showStatus={false}
      showUserInfo={false}
      showStar
      timeSort={0}
      type="star"
    />
  );
}

// mail-vue/src/views/star/index.vue
<template>
  <div class="email-view">
    <MobileAccountSelector />
    <emailScroll type="star" ref="scroll"
                 :allow-star="false"
                 :cancel-success="cancelStar"
                 :getEmailList="starList"
                 :emailDelete="emailDelete"
                 :star-add="starAdd"
                 :star-cancel="starCancel"
                 @jump="jumpContent"
                 actionLeft="6px"
                 :show-account-icon="false"
    />
  </div>
</template>

<script setup>
import emailScroll from "@/components/email-scroll/index.vue"
import MobileAccountSelector from "@/components/mobile-account-selector/index.vue"
import {emailDelete} from "@/request/email.js";
import {starAdd, starCancel, starList} from "@/request/star.js";
import {useEmailStore} from "@/store/email.js";
import {defineOptions, onMounted, ref} from "vue";
import router from "@/router/index.js";

defineOptions({
  name: 'star'
})

const scroll = ref({})
const emailStore = useEmailStore();

function jumpContent(email) {
  emailStore.contentData.email = email
  emailStore.contentData.delType = 'logic'
  emailStore.contentData.showStar = true
  emailStore.contentData.showReply = true
  router.push('/message')
}

function cancelStar(email) {
  emailStore.cancelStarEmailId = email.emailId
  scroll.value.deleteEmail([email.emailId])
}

onMounted(() => {
  emailStore.starScroll = scroll
})

</script>

<style scoped>
.email-view {
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.email-view :deep(.email-container) {
  flex: 1;
  min-height: 0;
}
</style>
