// mail-react/src/views/signature/index.tsx
import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Icon } from '@iconify/react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import HtmlEditor, { type HtmlEditorHandle } from '@/components/tiptap-editor';
import ShadowHtml from '@/components/shadow-html';
import { signatureList, signatureSet } from '@/request/signature';
import { useSignatureStore } from '@/store/signature';

export default function SignatureView() {
  const { t } = useTranslation();
  const signatureStore = useSignatureStore();
  const [signatures, setSignatures] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [editorShow, setEditorShow] = useState(false);
  const [previewShow, setPreviewShow] = useState(false);
  const editorRef = useRef<HtmlEditorHandle>(null);
  const [form, setForm] = useState({ domain: '', content: '', enabled: 1 });

  useEffect(() => {
    loadList();
  }, []);

  function loadList() {
    setLoading(true);
    signatureList()
      .then(setSignatures)
      .finally(() => setLoading(false));
  }

  function openEditor(row: any) {
    setForm({
      domain: row.domain,
      content: row.content || '',
      enabled: row.enabled ?? 1,
    });
    setEditorShow(true);
    setTimeout(() => editorRef.current?.clearEditor(), 0);
  }

  function openPreview() {
    setForm((f) => ({ ...f, content: editorRef.current?.getContent() ?? f.content }));
    setPreviewShow(true);
  }

  async function saveSignature() {
    const content = editorRef.current?.getContent() ?? form.content;
    setSaving(true);
    try {
      await signatureSet({ ...form, content });
      toast.success(t('saveSuccessMsg'));
      signatureStore.refreshSignature();
      setEditorShow(false);
      loadList();
    } finally {
      setSaving(false);
    }
  }

  function contentText(content: string = '') {
    return content.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
  }

  return (
    <div className="signature-box">
      <div className="header-actions">
        <Icon
          className="icon"
          icon="ion:reload"
          width="18"
          height="18"
          onClick={loadList}
          style={{ cursor: 'pointer' }}
        />
      </div>
      <div className="signature-scrollbar">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead style={{ width: 10 }} />
              <TableHead className="min-w-[180px]">{t('domain')}</TableHead>
              <TableHead style={{ width: 120 }}>{t('status')}</TableHead>
              <TableHead className="min-w-[220px]">{t('preview')}</TableHead>
              <TableHead style={{ width: 120 }}>{t('action')}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {signatures.length === 0 && !loading ? (
              <TableRow>
                <TableCell colSpan={5} className="py-8 text-center">
                  <div className="flex flex-col items-center gap-1.5 text-muted-foreground">
                    <Icon icon="lucide:signature" width="20" height="20" />
                    <div className="text-[13px] font-medium text-foreground">
                      {t('noSignatureFound')}
                    </div>
                  </div>
                </TableCell>
              </TableRow>
            ) : null}
            {signatures.map((row) => (
              <TableRow key={row.domain}>
                <TableCell />
                <TableCell>@{row.domain}</TableCell>
                <TableCell>
                  <Badge variant={row.enabled ? 'default' : 'secondary'}>
                    {row.enabled ? t('enabled') : t('disabled')}
                  </Badge>
                </TableCell>
                <TableCell>
                  <div className="content-preview">{contentText(row.content) || '-'}</div>
                </TableCell>
                <TableCell>
                  <Button size="sm" onClick={() => openEditor(row)}>
                    {t('change')}
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <Dialog open={editorShow} onOpenChange={setEditorShow}>
        <DialogContent className="max-w-[860px]">
          <DialogHeader>
            <DialogTitle>
              {t('signature')} - @{form.domain}
            </DialogTitle>
          </DialogHeader>
          <div className="signature-form">
            <div className="signature-switch">
              <span>{t('status')}</span>
              <Switch
                checked={form.enabled === 1}
                onCheckedChange={(v) => setForm((f) => ({ ...f, enabled: v ? 1 : 0 }))}
              />
            </div>
            <HtmlEditor
              ref={editorRef}
              defaultValue={form.content}
              onChange={(content) => setForm((f) => ({ ...f, content }))}
            />
            <div className="dialog-actions">
              <Button variant="outline" onClick={openPreview}>
                {t('preview')}
              </Button>
              <Button onClick={saveSignature} disabled={saving}>
                {t('save')}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      <Dialog open={previewShow} onOpenChange={setPreviewShow}>
        <DialogContent className="max-w-[860px]">
          <DialogHeader>
            <DialogTitle>{t('preview')}</DialogTitle>
          </DialogHeader>
          <div className="preview-box">
            <ShadowHtml html={form.content || ''} />
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// mail-vue/src/views/signature/index.vue
<template>
  <div class="signature-box">
    <div class="header-actions">
      <Icon class="icon" icon="ion:reload" width="18" height="18" @click="loadList"/>
    </div>
    <el-scrollbar class="signature-scrollbar">
      <el-table :data="signatures" style="height: 100%;" :empty-text="''" v-loading="loading">
        <el-table-column width="10"/>
        <el-table-column :label="$t('domain')" prop="domain" min-width="180">
          <template #default="props">
            <span>@{{ props.row.domain }}</span>
          </template>
        </el-table-column>
        <el-table-column :label="$t('status')" width="120">
          <template #default="props">
            <el-tag :type="props.row.enabled ? 'success' : 'info'">
              {{ props.row.enabled ? $t('enabled') : $t('disabled') }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column :label="$t('preview')" min-width="220">
          <template #default="props">
            <div class="content-preview">{{ contentText(props.row.content) || '-' }}</div>
          </template>
        </el-table-column>
        <el-table-column :label="$t('action')" width="120">
          <template #default="props">
            <el-button size="small" type="primary" @click="openEditor(props.row)">
              {{ $t('change') }}
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-scrollbar>

    <el-dialog v-model="editorShow" :title="`${$t('signature')} - @${form.domain}`" top="5vh" @closed="resetForm">
      <div class="signature-form">
        <div class="signature-switch">
          <span>{{ $t('status') }}</span>
          <el-switch v-model="form.enabled" :active-value="1" :inactive-value="0"/>
        </div>
        <tinyEditor :def-value="editorValue" ref="editor" @change="contentChange"/>
        <div class="dialog-actions">
          <el-button @click="openPreview">{{ $t('preview') }}</el-button>
          <el-button v-perm="'signature:set'" type="primary" :loading="saving" @click="saveSignature">
            {{ $t('save') }}
          </el-button>
        </div>
      </div>
    </el-dialog>

    <el-dialog v-model="previewShow" :title="$t('preview')" top="8vh">
      <div class="preview-box">
        <shadowHtml :html="previewHtml"/>
      </div>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, defineOptions, nextTick, reactive, ref } from 'vue';
import { Icon } from '@iconify/vue';
import tinyEditor from '@/components/tiny-editor/index.vue';
import shadowHtml from '@/components/shadow-html/index.vue';
import { signatureList, signatureSet } from '@/request/signature.js';
import { useI18n } from 'vue-i18n';
import { useSignatureStore } from '@/store/signature.js';

defineOptions({
  name: 'signature'
})

const { t } = useI18n();
const signatureStore = useSignatureStore();
const signatures = ref([]);
const loading = ref(false);
const saving = ref(false);
const editorShow = ref(false);
const previewShow = ref(false);
const editor = ref({});
const editorValue = ref('');
const form = reactive({
  domain: '',
  content: '',
  enabled: 1
});

const previewHtml = computed(() => form.content || '');

loadList();

function loadList() {
  loading.value = true;
  signatureList().then(list => {
    signatures.value = list;
  }).finally(() => {
    loading.value = false;
  });
}

function openEditor(row) {
  form.domain = row.domain;
  form.content = row.content || '';
  form.enabled = row.enabled ?? 1;
  editorValue.value = '';
  editorShow.value = true;
  nextTick(() => {
    editorValue.value = form.content;
  });
}

function contentChange(content) {
  form.content = content;
}

function openPreview() {
  form.content = editor.value.getContent();
  previewShow.value = true;
}

function saveSignature() {
  form.content = editor.value.getContent();
  saving.value = true;
  signatureSet({...form}).then(() => {
    ElMessage({
      message: t('saveSuccessMsg'),
      type: 'success',
      plain: true
    });
    signatureStore.refreshSignature();
    editorShow.value = false;
    loadList();
  }).finally(() => {
    saving.value = false;
  });
}

function resetForm() {
  form.domain = '';
  form.content = '';
  form.enabled = 1;
  previewShow.value = false;
}

function contentText(content = '') {
  return content.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
}
</script>

<style scoped lang="scss">
.signature-box {
  height: 100%;
  overflow: hidden;
  width: 100%;

  .signature-scrollbar {
    height: calc(100% - 42px);
  }
}

.header-actions {
  padding: 9px 15px;
  display: flex;
  align-items: center;
  gap: 18px;
  box-shadow: var(--header-actions-border);
  font-size: 18px;

  .icon {
    cursor: pointer;
  }
}

.content-preview {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.signature-form {
  height: min(600px, calc(90vh - 160px));
  display: grid;
  grid-template-rows: auto 1fr auto;
  gap: 14px;
}

.signature-switch {
  display: flex;
  align-items: center;
  gap: 12px;
}

.dialog-actions {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}

.preview-box {
  height: min(520px, calc(80vh - 120px));
  border: 1px solid var(--el-border-color-light);
  border-radius: 6px;
  padding: 12px;
  overflow: auto;
}

:deep(.el-dialog) {
  width: min(860px, calc(100% - 40px)) !important;
}
</style>
