// mail-react/src/components/account-member-dialog.tsx
import { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Icon } from '@iconify/react';
import { toast } from 'sonner';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import {
  accountMemberAdd,
  accountMemberList,
  accountMemberRemove,
  accountMemberSetRole,
  type AccountMember,
} from '@/request/account';

interface AccountMemberDialogProps {
  open: boolean;
  accountId: number;
  accountEmail: string;
  canManage: boolean;
  onClose: () => void;
}

type MemberRole = 'viewer' | 'sender' | 'admin';

const ROLE_OPTIONS: { value: MemberRole }[] = [
  { value: 'viewer' },
  { value: 'sender' },
  { value: 'admin' },
];

const roleKey = (r: MemberRole) =>
  `role${r.charAt(0).toUpperCase()}${r.slice(1)}` as 'roleViewer' | 'roleSender' | 'roleAdmin';

export default function AccountMemberDialog({
  open,
  accountId,
  accountEmail,
  canManage,
  onClose,
}: AccountMemberDialogProps) {
  const { t } = useTranslation();
  const [members, setMembers] = useState<AccountMember[]>([]);
  const [loading, setLoading] = useState(false);
  const [addEmail, setAddEmail] = useState('');
  const [addRole, setAddRole] = useState<MemberRole>('sender');
  const [removing, setRemoving] = useState<AccountMember | null>(null);

  const refresh = useCallback(async () => {
    if (!open) return;
    setLoading(true);
    try {
      const list = await accountMemberList(accountId);
      setMembers(list || []);
    } catch {
      /* interceptor */
    } finally {
      setLoading(false);
    }
  }, [open, accountId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  async function submitAdd() {
    if (!addEmail) return;
    try {
      await accountMemberAdd(accountId, addEmail, addRole);
      toast.success(t('setSuccess'));
      setAddEmail('');
      refresh();
    } catch {
      /* interceptor */
    }
  }

  async function changeRole(member: AccountMember, role: MemberRole) {
    try {
      await accountMemberSetRole(accountId, member.userId, role);
      toast.success(t('setSuccess'));
      refresh();
    } catch {
      /* interceptor */
    }
  }

  async function confirmRemove() {
    if (!removing) return;
    try {
      await accountMemberRemove(accountId, removing.userId);
      toast.success(t('setSuccess'));
      setRemoving(null);
      refresh();
    } catch {
      /* interceptor */
    }
  }

  return (
    <>
      <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
        <DialogContent className="max-w-[640px]">
          <DialogHeader>
            <DialogTitle>
              {t('memberManagement')} · <span className="text-muted-foreground">{accountEmail}</span>
            </DialogTitle>
          </DialogHeader>

          {canManage && (
            <div className="flex items-end gap-2">
              <div className="flex-1">
                <Input
                  placeholder={t('memberEmail')}
                  value={addEmail}
                  onChange={(e) => setAddEmail(e.target.value)}
                />
              </div>
              <div className="w-[140px]">
                <Select value={addRole} onValueChange={(v) => setAddRole(v as MemberRole)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {ROLE_OPTIONS.map((opt) => (
                      <SelectItem key={opt.value} value={opt.value}>
                        {t(roleKey(opt.value))}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <Button onClick={submitAdd}>{t('addMember')}</Button>
            </div>
          )}

          <div className="max-h-[400px] overflow-auto rounded-md border">
            <table className="w-full text-sm">
              <thead className="bg-muted text-muted-foreground">
                <tr className="text-left">
                  <th className="px-3 py-2 text-caption font-medium">{t('memberEmail')}</th>
                  <th className="px-3 py-2 text-caption font-medium">{t('memberRole')}</th>
                  <th className="px-3 py-2 text-caption font-medium"></th>
                </tr>
              </thead>
              <tbody>
                {members.map((m) => (
                  <tr key={m.userId} className="border-t">
                    <td className="px-3 py-2 font-mono text-num">{m.email}</td>
                    <td className="px-3 py-2">
                      {canManage ? (
                        <Select
                          value={(m.role || 'viewer') as MemberRole}
                          onValueChange={(v) => changeRole(m, v as MemberRole)}
                        >
                          <SelectTrigger className="h-7 w-[120px]">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            {ROLE_OPTIONS.map((opt) => (
                              <SelectItem key={opt.value} value={opt.value}>
                                {t(roleKey(opt.value))}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      ) : (
                        <Badge variant="secondary">
                          {t(roleKey((m.role || 'viewer') as MemberRole))}
                        </Badge>
                      )}
                    </td>
                    <td className="px-3 py-2 text-right">
                      <Icon
                        icon="ion:trash-outline"
                        width="18"
                        height="18"
                        className={cn(
                          'inline-block cursor-pointer text-muted-foreground hover:text-destructive',
                          !canManage && 'pointer-events-none opacity-30',
                        )}
                        onClick={() => canManage && setRemoving(m)}
                      />
                    </td>
                  </tr>
                ))}
                {!loading && members.length === 0 && (
                  <tr>
                    <td colSpan={3} className="px-3 py-6 text-center text-muted-foreground">
                      —
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={onClose}>
              {t('cancel')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <AlertDialog open={!!removing} onOpenChange={(o) => !o && setRemoving(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('removeMember')}</AlertDialogTitle>
            <AlertDialogDescription>{removing?.email}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t('cancel')}</AlertDialogCancel>
            <AlertDialogAction onClick={confirmRemove}>{t('confirm')}</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}

// Local utility to keep the file standalone
function cn(...classes: Array<string | undefined | false>) {
  return classes.filter(Boolean).join(' ');
}

// mail-vue/src/components/account-member-dialog.vue
<template>
  <el-dialog
      :model-value="open"
      :title="t('memberManagement') + ' · ' + accountEmail"
      width="640px"
      @close="onClose"
      @closed="resetForm"
  >
    <div class="member-add-row" v-if="canManage">
      <el-input
          v-model="addEmail"
          :placeholder="t('memberEmail')"
          class="member-email-input"
      />
      <el-select v-model="addRole" class="member-role-select">
        <el-option :key="'viewer'" :label="t('roleViewer')" :value="'viewer'"/>
        <el-option :key="'sender'" :label="t('roleSender')" :value="'sender'"/>
        <el-option :key="'admin'" :label="t('roleAdmin')" :value="'admin'"/>
      </el-select>
      <el-button type="primary" :loading="adding" @click="submitAdd">{{ t('addMember') }}</el-button>
    </div>
    <el-table :data="members" v-loading="loading" class="member-table" max-height="400">
      <el-table-column :label="t('memberEmail')" prop="email">
        <template #default="props">
          <span class="member-email-cell">{{ props.row.email }}</span>
        </template>
      </el-table-column>
      <el-table-column :label="t('memberRole')" :width="locale === 'en' ? 180 : 150">
        <template #default="props">
          <el-select
              v-if="canManage"
              :model-value="props.row.role || 'viewer'"
              class="member-role-edit"
              @change="(v) => changeRole(props.row, v)"
          >
            <el-option :key="'viewer'" :label="t('roleViewer')" :value="'viewer'"/>
            <el-option :key="'sender'" :label="t('roleSender')" :value="'sender'"/>
            <el-option :key="'admin'" :label="t('roleAdmin')" :value="'admin'"/>
          </el-select>
          <el-tag v-else type="info" disable-transitions>{{ roleLabel(props.row.role) }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column :width="locale === 'en' ? 70 : 60" align="right">
        <template #default="props">
          <Icon
              icon="ion:trash-outline"
              width="18"
              height="18"
              :class="['member-remove', !canManage && 'disabled']"
              @click="canManage && askRemove(props.row)"
          />
        </template>
      </el-table-column>
      <template #empty>
        <span class="member-empty">—</span>
      </template>
    </el-table>
    <template #footer>
      <el-button @click="onClose">{{ t('cancel') }}</el-button>
    </template>
  </el-dialog>
</template>

<script setup>
import {computed, ref, watch} from 'vue'
import {Icon} from '@iconify/vue'
import {useI18n} from 'vue-i18n'
import {
  accountMemberAdd,
  accountMemberList,
  accountMemberRemove,
  accountMemberSetRole,
} from '@/request/account.js'

const props = defineProps({
  open: {type: Boolean, default: false},
  accountId: {type: Number, required: true},
  accountEmail: {type: String, default: ''},
  canManage: {type: Boolean, default: false},
})

const emit = defineEmits(['close'])

const {t, locale} = useI18n()

const members = ref([])
const loading = ref(false)
const addEmail = ref('')
const addRole = ref('sender')
const adding = ref(false)

const roleLabel = (role) => {
  if (role === 'sender') return t('roleSender')
  if (role === 'admin') return t('roleAdmin')
  return t('roleViewer')
}

async function refresh() {
  if (!props.open) return
  loading.value = true
  try {
    const list = await accountMemberList(props.accountId)
    members.value = list || []
  } catch (e) {
    members.value = []
  } finally {
    loading.value = false
  }
}

watch(() => props.open, (val) => {
  if (val) refresh()
})

async function submitAdd() {
  if (!addEmail.value) return
  adding.value = true
  try {
    await accountMemberAdd(props.accountId, addEmail.value, addRole.value)
    addEmail.value = ''
    ElMessage({message: t('setSuccess'), type: 'success', plain: true})
    refresh()
  } finally {
    adding.value = false
  }
}

async function changeRole(member, role) {
  try {
    await accountMemberSetRole(props.accountId, member.userId, role)
    ElMessage({message: t('setSuccess'), type: 'success', plain: true})
    refresh()
  } catch (e) {}
}

function askRemove(member) {
  ElMessageBox.confirm(
      t('removeMember') + ' · ' + member.email,
      {confirmButtonText: t('confirm'), cancelButtonText: t('cancel'), type: 'warning'},
  ).then(async () => {
    try {
      await accountMemberRemove(props.accountId, member.userId)
      ElMessage({message: t('setSuccess'), type: 'success', plain: true})
      refresh()
    } catch (e) {}
  })
}

function resetForm() {
  members.value = []
  addEmail.value = ''
  addRole.value = 'sender'
}

function onClose() {
  emit('close')
}
</script>

<style scoped>
.member-add-row {
  display: flex;
  gap: 10px;
  margin-bottom: 15px;
}

.member-email-input {
  flex: 1;
}

.member-role-select {
  width: 130px;
}

.member-email-cell {
  font-family: var(--el-font-family-monospace, monospace);
}

.member-role-edit {
  width: 120px;
}

.member-remove {
  cursor: pointer;
  color: var(--regular-text-color);
  transition: color 200ms;
}

.member-remove:hover {
  color: var(--el-color-danger);
}

.member-remove.disabled {
  cursor: not-allowed;
  opacity: 0.3;
}

.member-empty {
  display: inline-block;
  color: var(--regular-text-color);
}

.member-table :deep(.cell) {
  word-break: break-all;
}
</style>
