// mail-react/src/views/draft/index.tsx
import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import EmailScroll, { type EmailScrollHandle, type EmailRowData } from '@/components/email-scroll';
import { starAdd as starAddFn, starCancel as starCancelFn } from '@/request/star';
import { useDraftStore } from '@/store/draft';
import { useUiStore } from '@/store/ui';
import { getDB, type DraftRecord, type AttRecord } from '@/db/db';

export default function DraftView() {
  const { t } = useTranslation();
  const refreshListCounter = useDraftStore((s) => s.refreshList);
  const openWriter = useUiStore((s) => s.openWriter);
  const scrollRef = useRef<EmailScrollHandle>(null);

  useEffect(() => {
    refreshList();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refreshListCounter]);

  async function refreshList() {
    const handle = scrollRef.current;
    if (!handle) return;
    const db = getDB();
    const drafts = await db.draft.orderBy('createTime').reverse().toArray();
    const list: EmailRowData[] = drafts.map((d) => ({
      emailId: -(d.draftId ?? 0),
      draftId: d.draftId,
      subject: d.subject,
      receiveEmail: d.toEmail.split(',').filter(Boolean),
      formatCreateTime: new Date(d.createTime).toISOString(),
      formatText: '',
      content: d.content,
      checked: false,
      createTime: d.createTime,
      name: '',
      sendEmail: '',
      isStar: 0,
      unread: 1,
    }));
    (handle as any).emailList.splice(0, (handle as any).emailList.length);
    (handle as any).emailList.push(...list);
    (handle as any).firstLoad = false;
  }

  async function deleteDraft(draftIds: number[]) {
    const db = getDB();
    await db.draft.bulkDelete(draftIds);
    useDraftStore.setState((s) => ({ refreshList: s.refreshList + 1 }));
  }

  async function jumpContent(email: EmailRowData) {
    const db = getDB();
    const att: AttRecord | undefined = await db.att.get(email.draftId!);
    openWriter({
      draftId: email.draftId,
      subject: email.subject,
      receiveEmail: email.receiveEmail,
      content: (email as any).content ?? '',
      attachments: att?.atts ?? [],
    });
  }

  async function getEmailList() {
    const db = getDB();
    const drafts: DraftRecord[] = await db.draft.orderBy('createTime').reverse().toArray();
    return { list: drafts, total: drafts.length, latestEmail: null };
  }

  return (
    <EmailScroll
      ref={scrollRef}
      allowStar={false}
      getEmailList={getEmailList as any}
      emailDelete={async () => {}}
      starAdd={starAddFn}
      starCancel={starCancelFn}
      onJump={jumpContent}
      onDeleteDraft={deleteDraft}
      actionLeft="6px"
      showAccountIcon={false}
      showStatus={false}
      showUserInfo={false}
      showStar={false}
      timeSort={0}
      type="draft"
      showFirstLoading={false}
      nameSlot={(email) => (
        <span>
          {email.receiveEmail && email.receiveEmail.length > 0
            ? email.receiveEmail.join(',')
            : `(${t('noRecipient')})`}
        </span>
      )}
      subjectSlot={(email) =>
        email.subject ? <>{email.subject}</> : <>({t('noSubject')})</>
      }
    />
  );
}

// mail-vue/src/views/draft/index.vue
<template>
  <div class="email-view">
    <MobileAccountSelector />
    <emailScroll ref="scroll"
                 :allow-star="false"
                 :getEmailList="getEmailList"
                 :emailDelete="emailDelete"
                 :star-add="starAdd"
                 :star-cancel="starCancel"
                 @jump="jumpContent"
                 actionLeft="6px"
                 :show-account-icon="false"
                 :show-first-loading="false"
                 :showStar="false"
                 @delete-draft="deleteDraft"
                 :type="'draft'"
    >
      <template #name="props">
        <span class="send-email">{{ props.email.receiveEmail?.join(',') || '(' + $t('noRecipient') + ')' }}</span>
      </template>
      <template #subject="props">
        {{ props.email.subject || '(' + $t('noSubject') + ')' }}
      </template>
    </emailScroll>
  </div>
</template>

<script setup>
import emailScroll from "@/components/email-scroll/index.vue"
import MobileAccountSelector from "@/components/mobile-account-selector/index.vue"
import {emailDelete} from "@/request/email.js";
import {starAdd, starCancel} from "@/request/star.js";
import {defineOptions, ref, watch, toRaw} from "vue";
import {useUiStore} from "@/store/ui.js";
import {userDraftStore} from "@/store/draft.js";
import db from "@/db/db.js"

defineOptions({
  name: 'draft'
})

const draftStore = userDraftStore();
const uiStore = useUiStore();
const scroll = ref({})

watch(() => draftStore.setDraft, async () => {

  const draft = toRaw(draftStore.setDraft)
  const draftId = draft.draftId
  const attachments = toRaw(draftStore.setDraft.attachments)

  delete draft.draftId
  delete draft.attachments

  if (!draft.content && !draft.subject && !(draft.receiveEmail.length > 0)) {
    await db.value.draft.delete(draftId);
    await db.value.att.delete(draftId);
    draftStore.refreshList++
    return;
  }

  await db.value.draft.update(draftId, draft);
  await db.value.att.update(draftId, {attachments: attachments});
  draftStore.refreshList++
}, {
  deep: true
})

watch(() => draftStore.refreshList, async () => {
  const {list} = await getEmailList();
    scroll.value.emailList.length = 0
    scroll.value.handleList(list);
    scroll.value.emailList.push(...list)
})

function getEmailList() {
  return new Promise((resolve, reject) => {
    db.value.draft.orderBy('createTime').reverse().toArray().then(list => {
      resolve({list})
    })
  })
}

async function deleteDraft(draftIds) {
  await db.value.draft.bulkDelete(draftIds);
  draftStore.refreshList++
}

async function jumpContent(email) {
  const att = await db.value.att.get(email.draftId)
  email.attachments = att.attachments
  uiStore.writerRef.openDraft(email);
}

</script>
<style>
.send-email {
  font-weight: normal;
}
</style>

<style scoped>
.email-view {
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.email-view :deep(.email-container) {
  flex: 1;
  min-height: 0;
}
</style>
