// mail-react/src/views/content/index.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Icon } from '@iconify/react';
import { toast } from 'sonner';
import ShadowHtml from '@/components/shadow-html';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/empty-state';
import { emailDelete, emailRead } from '@/request/email';
import { allEmailDelete } from '@/request/all-email';
import { starAdd, starCancel } from '@/request/star';
import { useEmailStore } from '@/store/email';
import { useAccountStore } from '@/store/account';
import { useSettingStore } from '@/store/setting';
import { useUiStore } from '@/store/ui';
import { formatDetailDate } from '@/utils/day';
import { formatBytes, getExtName } from '@/utils/file-utils';
import { cvtR2Url, toOssDomain } from '@/utils/convert';
import { getIconByName } from '@/utils/icon-utils';
import { hasPerm } from '@/perm';
import { EmailUnreadEnum } from '@/enums/email-enum';

export default function ContentView() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const emailStore = useEmailStore();
  const account = useAccountStore();
  const settings = useSettingStore((s) => s.settings);
  const openWriter = useUiStore((s) => s.openWriter);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [lightbox, setLightbox] = useState<string | null>(null);

  const data = emailStore.contentData;
  const email = data?.email;

  useEffect(() => {
    if (data?.showUnread && email && email.unread === EmailUnreadEnum.UNREAD) {
      email.unread = EmailUnreadEnum.READ;
      void emailRead([email.emailId]);
    }
    return () => {
      if (data?.showUnread) {
        useEmailStore.setState({
          contentData: {
            email: email ?? null,
            delType: 'logic',
            showStar: data.showStar,
            showReply: data.showReply,
          },
        });
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!account.currentAccountId) return;
    navigate(-1);
  }, [account.currentAccountId, navigate]);

  if (!email) {
    return (
      <div className="flex h-full items-center justify-center">
        <EmptyState
          icon="lucide:mail-x"
          title={t('noMessagesFound')}
          description={t('noMessagesFoundDesc')}
          className="py-16"
        >
          <Button variant="outline" size="sm" onClick={() => navigate('/inbox')}>
            <Icon icon="material-symbols-light:arrow-back-ios-new" width="14" height="14" />
            {t('backToInbox')}
          </Button>
        </EmptyState>
      </div>
    );
  }

  function openReply() {
    openWriter({ replyTo: email });
  }

  function openForward() {
    openWriter({ forwardFrom: email });
  }

  async function changeStar() {
    if (email.isStar) {
      email.isStar = 0;
      try {
        await starCancel(email.emailId);
        useEmailStore.setState({ cancelStarEmailId: email.emailId });
        setTimeout(() => useEmailStore.setState({ cancelStarEmailId: 0 }), 0);
        useEmailStore.getState().starScroll?.deleteEmail([email.emailId]);
      } catch {
        email.isStar = 1;
      }
    } else {
      email.isStar = 1;
      try {
        await starAdd(email.emailId);
        useEmailStore.setState({ addStarEmailId: email.emailId });
        setTimeout(() => useEmailStore.setState({ addStarEmailId: 0 }), 0);
        useEmailStore.getState().starScroll?.addItem(email);
      } catch {
        email.isStar = 0;
      }
    }
  }

  async function confirmDelete() {
    try {
      if (data.delType === 'logic') {
        await emailDelete([email.emailId]);
      } else {
        await allEmailDelete([email.emailId]);
      }
      toast.success(t('delSuccessMsg'));
      useEmailStore.setState({ deleteIds: email.emailId });
      navigate(-1);
    } catch {
      /* axios toasts */
    }
  }

  function formatImage(content: string) {
    content = content || '';
    const domain = settings?.r2Domain;
    return content.replace(/{{domain}}/g, toOssDomain(domain as string | undefined) + '/');
  }

  function isImage(filename: string) {
    return ['png', 'jpg', 'jpeg', 'bmp', 'gif', 'jfif'].includes(getExtName(filename));
  }

  function showImage(key: string) {
    if (!isImage(key)) return;
    setLightbox(cvtR2Url(key));
  }

  function formateReceive(recipient: any) {
    try {
      const arr = JSON.parse(recipient);
      return (arr as Array<{ address: string }>).map((i) => i.address).join(', ');
    } catch {
      return recipient;
    }
  }

  function toMessage(message: string) {
    try {
      return JSON.parse(message)?.message ?? '';
    } catch {
      return '';
    }
  }

  return (
    <div className="grid h-full grid-rows-[auto_1fr] overflow-hidden">
      <div className="flex items-center gap-5 border-b border-border px-4 py-2 text-lg">
        <Icon
          icon="material-symbols-light:arrow-back-ios-new"
          width="20"
          height="20"
          className="cursor-pointer"
          onClick={() => navigate(-1)}
        />
        {hasPerm('email:delete') && (
          <Icon
            icon="uiw:delete"
            width="16"
            height="16"
            className="cursor-pointer"
            onClick={() => setDeleteOpen(true)}
          />
        )}
        {data.showStar && (
          <span className="flex min-w-[21px] items-center justify-center">
            <Icon
              icon={email.isStar ? 'fluent-color:star-16' : 'solar:star-line-duotone'}
              width={email.isStar ? 20 : 18}
              height={email.isStar ? 20 : 18}
              className="cursor-pointer"
              onClick={changeStar}
            />
          </span>
        )}
        {data.showReply && hasPerm('email:send') && (
          <>
            <Icon
              icon="la:reply"
              width="21"
              height="21"
              className="cursor-pointer"
              onClick={openReply}
            />
            <Icon
              icon="iconoir:arrow-up-right"
              width="20"
              height="20"
              className="cursor-pointer"
              onClick={openForward}
            />
          </>
        )}
      </div>

      <div className="overflow-auto px-4 pt-2 text-sm">
        <div className="mb-3 text-xl font-bold">{email.subject}</div>
        <div className="flex flex-col gap-2 border-b border-border pb-2 text-foreground">
          {email.status === 3 && (
            <Alert variant="destructive">
              <AlertTitle>{t('delivered')}</AlertTitle>
              <AlertDescription>{toMessage(email.message)}</AlertDescription>
            </Alert>
          )}
          {email.status === 4 && (
            <Alert>
              <AlertTitle>{t('complained')}</AlertTitle>
            </Alert>
          )}
          {email.status === 5 && (
            <Alert>
              <AlertTitle>{t('delayed')}</AlertTitle>
            </Alert>
          )}
          <div className="mb-1.5 flex">
            <span className="whitespace-nowrap pr-2.5 font-bold">{t('from')}</span>
            <div className="flex flex-wrap text-muted-foreground">
              <span className="pr-1.5">{email.name}</span>
              <span>&lt;{email.sendEmail}&gt;</span>
            </div>
          </div>
          <div className="mb-1.5 flex">
            <span className="whitespace-nowrap pr-2.5 font-bold">{t('recipient')}</span>
            <span className="max-w-[700px] break-words text-muted-foreground">
              {formateReceive(email.recipient)}
            </span>
          </div>
          <div className="mb-1.5 text-muted-foreground">{formatDetailDate(email.createTime)}</div>
        </div>

        <div className="mb-7 mt-5">
          {email.content ? (
            <ShadowHtml html={formatImage(email.content)} />
          ) : (
            <pre className="m-0 whitespace-pre-wrap break-words font-sans">{email.text}</pre>
          )}
        </div>

        {email.attList && email.attList.length > 0 && (
          <div className="mb-7 mt-7 w-fit min-w-[410px] max-w-[600px] rounded-md border border-border p-3">
            <div className="mb-2 flex justify-between">
              <span className="font-bold">{t('attachments')}</span>
              <span>{t('attCount', { total: email.attList.length })}</span>
            </div>
            <div className="flex flex-col gap-3">
              {email.attList.map((att: any) => (
                <div
                  key={att.attId}
                  className="grid cursor-pointer grid-cols-[auto_1fr_auto_auto] items-center gap-2 rounded bg-muted px-2 py-1"
                  onClick={() => showImage(att.key)}
                >
                  <div className="flex items-center">
                    <Icon
                      {...(getIconByName(att.filename) as any)}
                      width={22}
                      height={22}
                    />
                  </div>
                  <div className="mx-2 truncate">{att.filename}</div>
                  <div className="whitespace-nowrap text-muted-foreground">
                    {formatBytes(att.size)}
                  </div>
                  <div className="flex items-center gap-2 pl-2.5">
                    {isImage(att.filename) && (
                      <Icon
                        icon="hugeicons:view"
                        width="22"
                        height="22"
                        className="cursor-pointer"
                        onClick={(e) => {
                          e.stopPropagation();
                          showImage(att.key);
                        }}
                      />
                    )}
                    <a
                      href={cvtR2Url(att.key)}
                      download
                      onClick={(e) => e.stopPropagation()}
                      className="text-muted-foreground"
                    >
                      <Icon icon="system-uicons:push-down" width="22" height="22" />
                    </a>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {lightbox && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80"
          onClick={() => setLightbox(null)}
        >
          <img
            src={lightbox}
            alt=""
            className="max-h-[90vh] max-w-[90vw] object-contain"
            onClick={(e) => e.stopPropagation()}
          />
          <Button
            variant="ghost"
            className="absolute right-4 top-4"
            onClick={() => setLightbox(null)}
          >
            ✕
          </Button>
        </div>
      )}

      <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('delete')}</AlertDialogTitle>
            <AlertDialogDescription>{t('delEmailConfirm')}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t('cancel')}</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete}>{t('confirm')}</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// mail-vue/src/views/content/index.vue
<template>
  <div class="box">
    <div class="header-actions">
      <Icon class="icon" icon="material-symbols-light:arrow-back-ios-new" width="20" height="20" @click="handleBack"/>
      <Icon v-perm="'email:delete'" class="icon" icon="uiw:delete" width="16" height="16" @click="handleDelete"/>
      <span class="star" v-if="emailStore.contentData.showStar">
        <Icon class="icon" @click="changeStar" v-if="email.isStar" icon="fluent-color:star-16" width="20" height="20"/>
        <Icon class="icon" @click="changeStar" v-else icon="solar:star-line-duotone" width="18" height="18"/>
      </span>
      <Icon class="icon" v-if="emailStore.contentData.showReply" v-perm="'email:send'"  @click="openReply" icon="la:reply" width="21" height="21" />
      <Icon class="icon" v-if="emailStore.contentData.showReply" v-perm="'email:send'"  @click="openForward" icon="iconoir:arrow-up-right" width="20" height="20" />
    </div>
    <div></div>
    <el-scrollbar class="scrollbar">
      <div class="container">
        <div class="email-title">
          {{ email.subject }}
        </div>
        <div class="content">
          <div class="email-info">
            <div>
              <div class="send"><span class="send-source">{{$t('from')}}</span>
                <div class="send-name">
                  <span class="send-name-title">{{ email.name }}</span>
                  <span><{{ email.sendEmail }}></span>
                </div>
              </div>
              <div class="receive"><span class="source">{{$t('recipient')}}</span><span class="receive-email">{{  formateReceive(email.recipient) }}</span></div>
              <div class="date">
                <div>{{ formatDetailDate(email.createTime) }}</div>
              </div>
            </div>
            <el-alert v-if="email.status === 3" :closable="false" :title="toMessage(email.message)" class="email-msg" type="error" show-icon />
            <el-alert v-if="email.status === 4" :closable="false" :title="$t('complained')" class="email-msg" type="warning" show-icon />
            <el-alert v-if="email.status === 5" :closable="false" :title="$t('delayed')" class="email-msg" type="warning" show-icon />
            <el-alert v-if="email.status === 8" :closable="false" :title="$t('sendFailed') + '：' + toMessage(email.message)" class="email-msg" type="error" show-icon />
          </div>
          <el-scrollbar class="htm-scrollbar" :class="email.attList.length === 0 ? 'bottom-distance' : ''">
            <ShadowHtml class="shadow-html" :html="formatImage(email.content)" v-if="email.content" />
            <pre v-else class="email-text" >{{email.text}}</pre>
          </el-scrollbar>
          <div class="att" v-if="email.attList.length > 0">
            <div class="att-title">
              <span>{{$t('attachments')}}</span>
              <span>{{$t('attCount',{total: email.attList.length})}}</span>
            </div>
            <div class="att-box">

              <div class="att-item" v-for="att in email.attList" :key="att.attId">
                <div class="att-icon" @click="showImage(att.key)">
                  <Icon v-bind="getIconByName(att.filename)" />
                </div>
                <div class="att-name" @click="showImage(att.key)">
                  {{ att.filename }}
                </div>
                <div class="att-size">{{ formatBytes(att.size) }}</div>
                <div class="opt-icon att-icon">
                  <Icon v-if="isImage(att.filename)" icon="hugeicons:view" width="22" height="22" @click="showImage(att.key)"/>
                  <a :href="cvtR2Url(att.key)" download>
                    <Icon icon="system-uicons:push-down" width="22" height="22"/>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </el-scrollbar>
    <el-image-viewer
        v-if="showPreview"
        :url-list="srcList"
        show-progress
        @close="showPreview = false"
    />
  </div>
</template>
<script setup>
import ShadowHtml from '@/components/shadow-html/index.vue'
import {reactive, ref, watch, onMounted, onUnmounted} from "vue";
import {useRouter} from 'vue-router'
import {ElMessage, ElMessageBox} from 'element-plus'
import {emailDelete, emailRead} from "@/request/email.js";
import {Icon} from "@iconify/vue";
import {useEmailStore} from "@/store/email.js";
import {useAccountStore} from "@/store/account.js";
import {formatDetailDate} from "@/utils/day.js";
import {starAdd, starCancel} from "@/request/star.js";
import {getExtName, formatBytes} from "@/utils/file-utils.js";
import {cvtR2Url,toOssDomain} from "@/utils/convert.js";
import {getIconByName} from "@/utils/icon-utils.js";
import {useSettingStore} from "@/store/setting.js";
import {allEmailDelete} from "@/request/all-email.js";
import {useUiStore} from "@/store/ui.js";
import {useI18n} from "vue-i18n";
import {EmailUnreadEnum} from "@/enums/email-enum.js";

const uiStore = useUiStore();
const settingStore = useSettingStore();
const accountStore = useAccountStore();
const emailStore = useEmailStore();
const router = useRouter()
const email = emailStore.contentData.email
const showPreview = ref(false)
const srcList = reactive([])

const { t } = useI18n()
watch(() => accountStore.currentAccountId, () => {
  handleBack()
})

onMounted(() => {
  if (emailStore.contentData.showUnread && email.unread === EmailUnreadEnum.UNREAD) {
    email.unread = EmailUnreadEnum.READ;
    emailRead([email.emailId]);
  }
})

onUnmounted(() => {
  emailStore.contentData.showUnread = false;
})

function openReply() {
  uiStore.writerRef.openReply(email)
}

function openForward() {
  uiStore.writerRef.openForward(email)
}

function toMessage(message) {
  return  message ? JSON.parse(message).message : '';
}

function formatImage(content) {
  content = content || '';
  const domain = settingStore.settings.r2Domain;
  return  content.replace(/{{domain}}/g, toOssDomain(domain) + '/');
}

function showImage(key) {
  if (!isImage(key)) return;
  const url = cvtR2Url(key)
  srcList.length = 0
  srcList.push(url)
  showPreview.value = true
}

function isImage(filename) {
  return ['png', 'jpg', 'jpeg', 'bmp', 'gif','jfif'].includes(getExtName(filename))
}

function formateReceive(recipient) {
  recipient = JSON.parse(recipient)
  return recipient.map(item => item.address).join(', ')
}

function changeStar() {
  if (email.isStar) {
    email.isStar = 0;
    starCancel(email.emailId).then(() => {
      email.isStar = 0;
      emailStore.cancelStarEmailId = email.emailId
      setTimeout(() => emailStore.cancelStarEmailId = 0)
      emailStore.starScroll?.deleteEmail([email.emailId])
    }).catch((e) => {
      console.error(e)
      email.isStar = 1;
    })
  } else {
    email.isStar = 1;
    starAdd(email.emailId).then(() => {
      email.isStar = 1;
      emailStore.addStarEmailId = email.emailId
      setTimeout(() => emailStore.addStarEmailId = 0)
      emailStore.starScroll?.addItem(email)
    }).catch((e) => {
      console.error(e)
      email.isStar = 0;
    })
  }
}

const handleBack = () => {
  router.back()
}

const handleDelete = () => {
  ElMessageBox.confirm(t('delEmailConfirm'), {
    confirmButtonText: t('confirm'),
    cancelButtonText: t('cancel'),
    type: 'warning'
  }).then(() => {
    if (emailStore.contentData.delType === 'logic') {
      emailDelete(email.emailId).then(() => {
        ElMessage({
          message: t('delSuccessMsg'),
          type: 'success',
          plain: true,
        })
        emailStore.deleteIds = [email.emailId]
      })
    } else  {

      allEmailDelete(email.emailId).then(() => {
        ElMessage({
          message: t('delSuccessMsg'),
          type: 'success',
          plain: true,
        })
        emailStore.deleteIds = [email.emailId]
      })
    }

    router.back()
  })
}
</script>
<style scoped lang="scss">
.box {
  height: 100%;
  overflow: hidden;
}

.header-actions {
  padding: 9px 15px 8px;
  display: flex;
  align-items: center;
  gap: 20px;
  box-shadow: var(--header-actions-border);
  font-size: 18px;
  .star {
    display: flex;
    align-items: center;
    justify-content: center;
    min-width: 21px;
  }
  .icon {
    cursor: pointer;
  }
}


.scrollbar {
  height: calc(100% - 38px);
  width: 100%;
}

.container {
  font-size: 14px;
  padding-left: 20px;
  padding-right: 20px;
  padding-top: 10px;
  @media (max-width: 1023px) {
    padding-left: 15px;
    padding-right: 15px;
  }

  .email-title {
    font-size: 20px;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .htm-scrollbar {
  }

  .content {
    display: flex;
    flex-direction: column;

    .att {
      margin-top: 30px;
      margin-bottom: 30px;
      border: 1px solid var(--light-border-color);
      padding: 14px;
      border-radius: 6px;
      width: fit-content;
      .att-box {
        min-width: min(410px,calc(100vw - 60px));
        max-width: 600px;
        display: grid;
        gap: 12px;
        grid-template-rows: 1fr;
      }

      .att-title {
        margin-bottom: 8px;
        display: flex;
        justify-content: space-between;
        span:first-child {
          font-weight: bold;
        }
      }

      .att-item {
        cursor: pointer;
        div {
          align-self: center;
        }
        background: var(--light-ill);
        padding: 5px 7px;
        border-radius: 4px;
        align-self: start;
        display: grid;
        grid-template-columns: auto 1fr auto auto;
        .att-icon {
          display: grid;
        }

        .att-size {
          color: var(--secondary-text-color);
        }

        .att-name {
          margin-left: 8px;
          margin-right: 8px;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
          word-break: break-all;
        }

        .att-image {
          width: 60px;
          height: 60px;
          object-fit: contain;
        }

        .opt-icon {
          padding-left: 10px;
          color: var(--secondary-text-color);
          align-items: center;
          display: flex;
          gap: 8px;
          cursor: pointer;
          a {
            color: var(--secondary-text-color);
            align-items: center;
            display: flex;
          }
        }
      }
    }

    .email-info {

      border-bottom: 1px solid var(--light-border-color);
      margin-bottom: 20px;
      padding-bottom: 8px;
      @media (max-width: 1024px) {
        margin-bottom: 15px;
      }
      .date {
        color: var(--regular-text-color);
        margin-bottom: 6px;
      }

      .email-msg {
        max-width: 400px;
        width: fit-content;
        margin-bottom: 15px;
      }

      .send {
        display: flex;
        margin-bottom: 6px;

        .send-name {
          color: var(--regular-text-color);
          display: flex;
          flex-wrap: wrap;
        }

        .send-name-title {
          padding-right: 5px;
        }
      }

      .receive {
        margin-bottom: 6px;
        display: flex;
        .receive-email {
          max-width: 700px;
          word-break: break-word;
        }
        span:nth-child(2) {
          color: var(--regular-text-color);
        }
      }

      .send-source {
        white-space: nowrap;
        font-weight: bold;
        padding-right: 10px;
      }

      .source {
        white-space: nowrap;
        font-weight: bold;
        padding-right: 10px;
      }
    }
  }
}

.shadow-html::after  {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: var(--message-block-color); /* 半透明黑色蒙层 */
  pointer-events: none; /* 不影响点击 */
}

.email-text {
  font-family: inherit;
  white-space: pre-wrap;
  word-break: break-word;
  margin: 0;
}

.bottom-distance {
  margin-bottom: 30px;
}


</style>
