// mail-vue/src/layout/account/index.vue
<template>
  <div class="account-box">
    <div class="head-opt">
      <Icon v-perm="'account:add'" class="icon add" icon="ion:add-outline" width="23" height="23" @click="add"/>
      <Icon class="icon refresh" icon="ion:reload" width="18" height="18" @click="refresh"/>
    </div>
    <el-scrollbar class="scrollbar" ref="scrollbarRef">
      <div v-infinite-scroll="getAccountList" :infinite-scroll-distance="600" :infinite-scroll-immediate="false">
        <el-card class="item" :class="itemBg(item.accountId)" v-for="(item, index) in accounts" :key="item.accountId"
                 @click="changeAccount(item)">
          <div class="account">
            <el-tag
                v-if="item.perm && item.perm !== 'owner'"
                :type="roleTagType(item.perm)"
                size="small"
                disable-transitions
                class="role-tag"
            >{{ permLabel(item.perm) }}</el-tag>
            <span>{{ item.email }}</span>
          </div>
          <div class="opt">
            <div class="send-email" @click.stop>
              <Icon @click="setAllReceive(item)" v-if="!item.allReceive" icon="eva:email-fill" width="22" height="22" color="#fccb1a"/>
              <Icon @click="setAllReceive(item)" v-else icon="flat-color-icons:folder" width="22" height="22" color="#23c4f1" />
            </div>
            <div class="settings" @click.stop>
              <Icon icon="fluent-color:clipboard-24" width="22" height="22" @click.stop="copyAccount(item.email)"/>
              <Icon icon="fluent:settings-24-filled" width="21" height="21" color="#909399"
                    v-if="showNullSetting(item)"/>
              <el-dropdown v-else>
                <Icon icon="fluent:settings-24-filled" width="21" height="21" color="#909399"/>
                <template #dropdown>
                  <el-dropdown-menu>
                    <el-dropdown-item
                        v-if="canManage(item) && hasPerm('email:send')"
                        @click="openSetName(item)"
                    >{{ $t('rename') }}</el-dropdown-item>
                    <el-dropdown-item
                        v-if="canManage(item)"
                        @click="openMembers(item)"
                    >{{ $t('memberManagement') }}</el-dropdown-item>
                    <el-dropdown-item
                        v-if="canManage(item) && item.accountId !== userStore.user.account.accountId"
                        @click="setAsTop(item, index)"
                    >{{ $t('pin') }}</el-dropdown-item>
                    <el-dropdown-item
                        v-if="item.perm === 'owner' && item.accountId !== userStore.user.account.accountId && hasPerm('account:delete')"
                        @click="remove(item)"
                    >{{ $t('delete') }}
                    </el-dropdown-item>
                  </el-dropdown-menu>
                </template>
              </el-dropdown>
            </div>
          </div>
        </el-card>

        <!-- Initial Loading Skeleton -->
        <template v-if="loading">
          <el-skeleton v-for="i in skeletonRows" :key="i" animated>
            <template #template>
              <el-card class="item">
                <el-skeleton-item variant="p" style="width: 70%; height: 20px; margin-bottom: 25px"/>
                <div style="display: flex; justify-content: space-between">
                  <el-skeleton-item variant="text" style="width: 20px"/>
                  <el-skeleton-item variant="text" style="width: 20px"/>
                </div>
              </el-card>
            </template>
          </el-skeleton>
        </template>

        <!-- Follow Loading Skeleton -->
        <template v-if="accounts.length > 0 && !noLoading">
          <el-skeleton animated>
            <template #template>
              <el-card class="item">
                <el-skeleton-item variant="p" style="width: 70%; height: 20px; margin-bottom: 20px"/>
                <div style="display: flex; justify-content: space-between">
                  <el-skeleton-item variant="text" style="width: 20px"/>
                  <el-skeleton-item variant="text" style="width: 20px"/>
                </div>
              </el-card>
            </template>
          </el-skeleton>
        </template>

        <div class="noLoading" v-if="noLoading && accounts.length > 0">
          <div>{{ $t('noMoreData') }}</div>
        </div>
        <div class="empty" v-if="noLoading && accounts.length === 0">
          <el-empty :description="$t('noMessagesFound')"/>
        </div>
      </div>

    </el-scrollbar>
    <el-dialog v-model="showAdd" :title="$t('addAccount')">
      <div class="container">
        <el-input v-model="addForm.email" ref="addRef" type="text" :placeholder="$t('emailAccount')" autocomplete="off">
          <template #append>
            <div @click.stop="openSelect">
              <el-select
                  ref="mySelect"
                  v-model="addForm.suffix"
                  :placeholder="$t('select')"
                  class="select"
              >
                <el-option
                    v-for="item in domainList"
                    :key="item"
                    :label="item"
                    :value="item"
                />
              </el-select>
              <div>
                <span>{{ addForm.suffix }}</span>
                <Icon class="setting-icon" icon="mingcute:down-small-fill" width="20" height="20"/>
              </div>
            </div>
          </template>
        </el-input>
        <el-button class="btn" type="primary" @click="submit" :loading="addLoading"
        >{{ $t('add') }}
        </el-button>
      </div>
      <div
          class="add-email-turnstile"
          :class="verifyShow ? 'turnstile-show' : 'turnstile-hide'"
          :data-sitekey="settingStore.settings.siteKey"
          data-callback="onTurnstileSuccess"
          data-error-callback="onTurnstileError"
      >
        <span style="font-size: 12px;color: #F56C6C" v-if="botJsError">{{ $t('verifyModuleFailed') }}</span>
      </div>
    </el-dialog>
    <el-dialog v-model="setNameShow" :title="$t('changeUserName')">
      <div class="container">
        <el-input v-model="accountName" type="text" :placeholder="$t('username')" autocomplete="off">
        </el-input>
        <el-button class="btn" type="primary" @click="setName" :loading="setNameLoading"
        >{{ $t('save') }}
        </el-button>
      </div>
    </el-dialog>

    <AccountMemberDialog
        v-if="memberTarget"
        :open="!!memberTarget"
        :account-id="memberTarget.accountId"
        :account-email="memberTarget.email"
        :can-manage="canManage(memberTarget)"
        @close="memberTarget = null"
    />
  </div>
</template>
<script setup>
import {Icon} from "@iconify/vue";
import {computed, nextTick, reactive, ref, watch} from "vue";
import {
  accountList,
  accountAdd,
  accountDelete,
  accountSetName,
  accountSetAllReceive,
  accountSetAsTop
} from "@/request/account.js";
import {sleep} from "@/utils/time-utils.js"
import {isEmail} from "@/utils/verify-utils.js";
import {useSettingStore} from "@/store/setting.js";
import {useAccountStore} from "@/store/account.js";
import {useEmailStore} from "@/store/email.js";
import {useUserStore} from "@/store/user.js";
import {hasPerm} from "@/perm/perm.js"
import {useI18n} from "vue-i18n";
import {AccountAllReceiveEnum} from "@/enums/account-enum.js";
import AccountMemberDialog from "@/components/account-member-dialog.vue";

const {t} = useI18n();
const userStore = useUserStore();
const accountStore = useAccountStore();
const settingStore = useSettingStore();
const emailStore = useEmailStore();
const showAdd = ref(false)
const addLoading = ref(false);
const domainList = computed(() => settingStore.domainList)
const accounts = reactive([])
const noLoading = ref(false)
const loading = ref(false)
const followLoading = ref(false);
const verifyShow = ref(false)
const setNameShow = ref(false)
const setNameLoading = ref(false)
const accountName = ref(null)
const addRef = ref({})
const scrollbarRef = ref({})
let account = null
let turnstileId = null
const botJsError = ref(false)
let verifyToken = ''
let verifyErrorCount = 0
let first = true
const addForm = reactive({
  email: '',
  suffix: settingStore.domainList[0]
})
let skeletonRows = 10
const queryParams = {
  size: 30
}

const mySelect = ref()

if (hasPerm('account:query')) {
  getAccountList()
}

watch(() => accountStore.changeUserAccountName, () => {
  accounts[0].name = accountStore.changeUserAccountName
})

watch(() => settingStore.domainList, (list) => {
  if (!addForm.suffix && list.length > 0) {
    addForm.suffix = list[0]
  }
}, {immediate: true})


const openSelect = () => {
  mySelect.value.toggleMenu()
}

window.onTurnstileError = (e) => {
  if (verifyErrorCount >= 4) {
    return
  }
  verifyErrorCount++
  console.warn('人机验加载失败', e)
  setTimeout(() => {
    nextTick(() => {
      if (!turnstileId) {
        turnstileId = window.turnstile.render('.add-email-turnstile')
      } else {
        window.turnstile.reset(turnstileId);
      }
    })
  }, 1500)
};

window.onTurnstileSuccess = (token) => {
  verifyToken = token;
};

function getSkeletonRows() {
  if (accounts.length > 20) return skeletonRows = 20
  if (accounts.length === 0) return skeletonRows = 1
  skeletonRows = accounts.length
}

function setName() {

  let name = accountName.value

  if (name === account.name) {
    setNameShow.value = false
    return
  }

  if (!name) {
    ElMessage({
      message: t('emptyUserNameMsg'),
      type: 'error',
      plain: true,
    })
    return;
  }

  setNameLoading.value = true
  accountSetName(account.accountId, name).then(() => {
    account.name = name
    setNameShow.value = false

    if (account.accountId === userStore.user.account.accountId) {
      userStore.user.name = name
    }

    ElMessage({
      message: t('saveSuccessMsg'),
      type: "success",
      plain: true
    })
  }).finally(() => {
    setNameLoading.value = false
  })
}

function openSetName(accountItem) {
  accountName.value = accountItem.name
  account = accountItem
  setNameShow.value = true
}

function setAllReceive(account) {
  let allReceiveAccount = accounts.find(account => account.allReceive === AccountAllReceiveEnum.ENABLED);
  if (allReceiveAccount && allReceiveAccount.accountId !== account.accountId) allReceiveAccount.allReceive = AccountAllReceiveEnum.DISABLED;
  account.allReceive = account.allReceive === AccountAllReceiveEnum.DISABLED ? AccountAllReceiveEnum.ENABLED : AccountAllReceiveEnum.DISABLED;
  accountSetAllReceive(account.accountId).catch(() => {
    account.allReceive = account.allReceive === AccountAllReceiveEnum.DISABLED ? AccountAllReceiveEnum.ENABLED : AccountAllReceiveEnum.DISABLED;
    if (allReceiveAccount) allReceiveAccount.allReceive = AccountAllReceiveEnum.ENABLED;
  }).then(() => {
    if (account.allReceive === AccountAllReceiveEnum.ENABLED) {
      ElMessage({
        message: t('setSuccess'),
        type: 'success',
        plain: true,
      })
    }
    changeAccount(account);
    emailStore.emailScroll?.refreshList();
    emailStore.sendScroll?.refreshList();
  })
}


function showNullSetting(item) {
  return !hasPerm('email:send')
      && !(item.accountId !== userStore.user.account.accountId && hasPerm('account:delete'))
      && !canManage(item)
}

function itemBg(accountId) {
  return accountStore.currentAccountId === accountId ? 'item-choose' : ''
}



function remove(account) {
  ElMessageBox.confirm(t('delConfirm', {msg: account.email}), {
    confirmButtonText: t('confirm'),
    cancelButtonText: t('cancel'),
    type: 'warning'
  }).then(() => {
    accountDelete(account.accountId).then(() => {
      const index = accounts.findIndex(item => item.accountId === account.accountId);
      accounts.splice(index, 1);
      if (accounts.length < queryParams.size) {
        getAccountList()
      }
      ElMessage({
        message: t('delSuccessMsg'),
        type: 'success',
        plain: true,
      })
    })
  });
}

function refresh() {
  if (loading.value) {
    return
  }
  loading.value = false
  followLoading.value = false
  noLoading.value = false
  queryParams.accountId = 0
  queryParams.lastSort = null
  getSkeletonRows();
  scrollbarRef.value.setScrollTop(0)
  accounts.splice(0, accounts.length)
  getAccountList()
}

function changeAccount(account) {
  accountStore.currentAccountId = account.accountId
  accountStore.currentAccount = account
}

function add() {
  addForm.suffix = addForm.suffix || settingStore.domainList[0]
  showAdd.value = true
  setTimeout(() => {
    addRef.value.focus()
  }, 100)
}

function setAsTop(account, index) {
  accountSetAsTop(account.accountId).then(() => {
    ElMessage({
      message: t('setSuccess'),
      type: 'success',
      plain: true,
    })

    const [item] = accounts.splice(index, 1);
    accounts.splice(1, 0, item);

  });
}

async function copyAccount(account) {
  try {
    await navigator.clipboard.writeText(account);
    ElMessage({
      message: t('copySuccessMsg'),
      type: 'success',
      plain: true,
    })
  } catch (err) {
    console.error(`${t('copyFailMsg')}:`, err);
    ElMessage({
      message: t('copyFailMsg'),
      type: 'error',
      plain: true,
    })
  }
}

const memberTarget = ref(null)

function canManage(item) {
  return item.perm === 'owner' || item.perm === 'admin'
}

function permLabel(perm) {
  if (perm === 'admin') return t('roleAdmin')
  if (perm === 'sender') return t('roleSender')
  if (perm === 'viewer') return t('roleViewer')
  return ''
}

function roleTagType(perm) {
  if (perm === 'admin') return ''
  return 'info'
}

function openMembers(item) {
  memberTarget.value = item
}

function getAccountList() {

  if (loading.value || followLoading.value || noLoading.value) return;

  if (accounts.length === 0) {
    loading.value = true
  } else {
    followLoading.value = true
  }

  let start = Date.now();

  const accountId = accounts.length > 0 ? accounts.at(-1).accountId : 0;
  const lastSort = accounts.length > 0 ? accounts.at(-1).sort : null;

  accountList(accountId, queryParams.size, lastSort).then(async list => {

    let end = Date.now();
    let duration = end - start;
    if (duration < 300) {
      await sleep(300 - duration)
    }

    if (list.length < queryParams.size) {
      noLoading.value = true
    }
    if (accounts.length === 0) {
      accountStore.currentAccount = list[0]
    }

    accounts.push(...list)

    loading.value = false
    followLoading.value = false
    first = false
  }).catch(() => {
    loading.value = false
    followLoading.value = false
  })
}


function submit() {

  if (!addForm.email) {
    ElMessage({
      message: t('emptyEmailMsg'),
      type: "error",
      plain: true
    })
    return
  }

  if (addForm.email.length < settingStore.settings.minEmailPrefix) {
    ElMessage({
      message: t('minEmailPrefix', {msg: settingStore.settings.minEmailPrefix}),
      type: 'error',
      plain: true,
    })
    return
  }

  if (!isEmail(addForm.email + addForm.suffix)) {
    ElMessage({
      message: t('notEmailMsg'),
      type: "error",
      plain: true
    })
    return
  }

  if (!verifyToken && (settingStore.settings.addEmailVerify === 0 || (settingStore.settings.addEmailVerify === 2 && settingStore.settings.addVerifyOpen))) {
    if (!verifyShow.value) {
      verifyShow.value = true
      nextTick(() => {
        if (!turnstileId) {
          try {
            turnstileId = window.turnstile.render('.add-email-turnstile')
          } catch (e) {
            botJsError.value = true
            console.log('人机验证js加载失败')
          }
        } else {
          window.turnstile.reset('.add-email-turnstile')
        }
      })
    } else if (!botJsError.value) {
      ElMessage({
        message: t('botVerifyMsg'),
        type: "error",
        plain: true
      })
    }
    return;
  }

  addLoading.value = true
  accountAdd(addForm.email + addForm.suffix, verifyToken).then(account => {
    addLoading.value = false
    showAdd.value = false
    addForm.email = ''
    accounts.push(account)
    verifyToken = ''
    settingStore.settings.addVerifyOpen = account.addVerifyOpen
    ElMessage({
      message: t('addSuccessMsg'),
      type: "success",
      plain: true
    })
    verifyShow.value = false
    userStore.refreshUserInfo()
  }).catch(res => {
    if (res.code === 400) {
      verifyToken = ''
      if (turnstileId) {
        window.turnstile.reset(turnstileId)
      } else {
        nextTick(() => {
          turnstileId = window.turnstile.render('.add-email-turnstile')
        })
      }
      verifyShow.value = true
    }
    addLoading.value = false
  })
}
</script>
<style>
path[fill="#ffdda1"] {
  fill: #ffdd7d;
}
</style>
<style scoped lang="scss">
.account-box {

  border-right: 1px solid var(--el-border-color) !important;
  background-color: var(--el-bg-color);
  height: 100%;
  overflow: hidden;

  .head-opt {
    display: flex;
    align-items: center;
    height: 38px;
    box-shadow: var(--header-actions-border);
    padding-left: 10px;
    padding-right: 10px;

    .icon {
      cursor: pointer;
    }

    .refresh {
      margin-left: 10px;
    }

    .add {
      margin-left: 2px;
    }

    .head-opt:not(.add) .refresh {
      margin-left: 5px;
    }
  }

  .scrollbar {
    width: 100%;
    height: calc(100% - 38px);
    overflow: auto;
    @media (max-width: 767px) {
      height: calc(100% - 98px);
    }

    .empty {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100%;
    }

    .noLoading {
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 10px 0;
      color: var(--secondary-text-color);
    }
  }

  .btn {
    width: 100%;
    margin-top: 15px;
  }

  .item {
    background-color: var(--el-bg-color);
    border-radius: 8px;
    padding: 12px 10px;
    margin-bottom: 10px;
    margin-left: 10px;
    margin-right: 10px;
    cursor: pointer;

    .account {
      font-weight: 600;
      margin-bottom: 20px;
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
      display: flex;
      align-items: center;
      gap: 8px;

      .role-tag {
        flex-shrink: 0;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        font-size: 10px;
        height: 18px;
        line-height: 18px;
        padding: 0 6px;
      }
    }

    .opt {
      display: flex;
      justify-content: space-between;
      font-size: 12px;
      color: #888;

      .settings {
        display: flex;
        align-items: center;
        gap: 10px;
      }

      .send-email {
        display: flex;
        align-items: center;
      }
    }

    :deep(.el-card__body) {
      padding: 0;
    }
  }

  .item:first-child {
    margin-top: 10px;
  }

  .item-choose {
    background: var(--choose-account-background);
  }
}


.setting-icon {
  position: relative;
  top: 6px;
}

:deep(.el-input-group__append) {
  padding: 0 !important;
  padding-left: 8px !important;
  background: var(--el-bg-color);
}

:deep(.el-dialog) {
  width: 400px !important;
  @media (max-width: 440px) {
    width: calc(100% - 40px) !important;
    margin-right: 20px !important;
    margin-left: 20px !important;
  }
}

.select {
  position: absolute;
  right: 30px;
  width: 100px;
  opacity: 0;
  pointer-events: none;
}

:deep(.el-pagination .el-select) {
  width: 100px;
  background: var(--el-bg-color);
}

.add-email-turnstile {
  margin-top: 15px;
}

.turnstile-show {
  opacity: 1;
}

.turnstile-hide {
  opacity: 0;
  pointer-events: none;
  position: fixed;
}

</style>

// mail-react/src/layouts/account.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { Icon } from '@iconify/react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { useAccountStore } from '@/store/account';
import { useUserStore } from '@/store/user';
import { hasPerm } from '@/perm';
import {
  accountAdd,
  accountDelete,
  accountList,
  accountSetAllReceive,
  accountSetAsTop,
  accountSetName,
  type AccountListItem,
  type AccountPerm,
} from '@/request/account';
import { cn } from '@/lib/utils';
import AccountMemberDialog from '@/components/account-member-dialog';

const PAGE_SIZE = 30;

interface AccountProps {
  className?: string;
}

export default function Account({ className }: AccountProps) {
  const { t } = useTranslation();
  const user = useUserStore((s) => s.user);
  const currentAccountId = useAccountStore((s) => s.currentAccountId);
  const setCurrentAccountId = useAccountStore((s) => s.setCurrentAccountId);
  const setCurrentAccount = useAccountStore((s) => s.setCurrentAccount);

  const [accounts, setAccounts] = useState<AccountListItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [noMore, setNoMore] = useState(false);
  const lastSortRef = useRef<number | undefined>(undefined);

  const [addOpen, setAddOpen] = useState(false);
  const [addEmail, setAddEmail] = useState('');
  const [renameTarget, setRenameTarget] = useState<AccountListItem | null>(null);
  const [renameValue, setRenameValue] = useState('');
  const [deleteTarget, setDeleteTarget] = useState<AccountListItem | null>(null);
  const [memberTarget, setMemberTarget] = useState<AccountListItem | null>(null);

  const permLabel = (perm: AccountPerm | undefined) => {
    if (perm === 'owner') return t('mailboxOwner');
    if (perm === 'admin') return t('roleAdmin');
    if (perm === 'sender') return t('roleSender');
    if (perm === 'viewer') return t('roleViewer');
    return null;
  };

  const canManage = (item: AccountListItem) =>
    item.perm === 'owner' || item.perm === 'admin';
  const canRename = (item: AccountListItem) =>
    item.perm === 'owner' || item.perm === 'admin';

  const loadMore = useCallback(async () => {
    if (loading || noMore) return;
    setLoading(true);
    try {
      const list = await accountList(0, PAGE_SIZE, lastSortRef.current);
      setAccounts((prev) => [...prev, ...list]);
      if (list.length < PAGE_SIZE) setNoMore(true);
      const last = list[list.length - 1];
      if (last) lastSortRef.current = (last as unknown as { sort?: number }).sort;
    } finally {
      setLoading(false);
    }
  }, [loading, noMore]);

  const refresh = useCallback(() => {
    setAccounts([]);
    setNoMore(false);
    lastSortRef.current = undefined;
    // trigger reload on next tick
    setTimeout(() => loadMoreRef.current(), 0);
  }, []);

  const loadMoreRef = useRef(loadMore);
  loadMoreRef.current = loadMore;

  useEffect(() => {
    loadMore();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function changeAccount(item: AccountListItem) {
    setCurrentAccountId(item.accountId);
    setCurrentAccount(item);
  }

  function onScroll(e: React.UIEvent<HTMLDivElement>) {
    const el = e.currentTarget;
    if (el.scrollHeight - el.scrollTop - el.clientHeight < 600) loadMore();
  }

  async function copyAccount(email: string) {
    try {
      await navigator.clipboard.writeText(email);
      toast.success(t('copySuccessMsg'));
    } catch {
      toast.error(t('copyFailMsg'));
    }
  }

  async function toggleAllReceive(item: AccountListItem) {
    await accountSetAllReceive(item.accountId);
    setAccounts((prev) =>
      prev.map((a) =>
        a.accountId === item.accountId ? { ...a, allReceive: a.allReceive ? 0 : 1 } : a,
      ),
    );
  }

  async function submitAdd() {
    if (!addEmail) return;
    try {
      await accountAdd(addEmail);
      toast.success(t('addSuccessMsg'));
      setAddOpen(false);
      setAddEmail('');
      refresh();
    } catch {
      /* interceptor toasts */
    }
  }

  async function submitRename() {
    if (!renameTarget) return;
    await accountSetName(renameTarget.accountId, renameValue);
    setAccounts((prev) =>
      prev.map((a) => (a.accountId === renameTarget.accountId ? { ...a, name: renameValue } : a)),
    );
    setRenameTarget(null);
  }

  async function setAsTop(item: AccountListItem) {
    await accountSetAsTop(item.accountId);
    refresh();
  }

  async function confirmDelete() {
    if (!deleteTarget) return;
    await accountDelete(deleteTarget.accountId);
    setAccounts((prev) => prev.filter((a) => a.accountId !== deleteTarget.accountId));
    setDeleteTarget(null);
  }

  const selfAccountId = user?.account?.accountId;

  return (
    <div className={cn('flex h-full flex-col border-r border-border bg-background', className)}>
      <div className="flex items-center justify-end gap-3 border-b border-border p-2">
        {hasPerm('account:add') && (
          <Icon
            className="cursor-pointer text-muted-foreground hover:text-foreground"
            icon="ion:add-outline"
            width="23"
            height="23"
            onClick={() => setAddOpen(true)}
          />
        )}
        <Icon
          className="cursor-pointer text-muted-foreground hover:text-foreground"
          icon="ion:reload"
          width="18"
          height="18"
          onClick={refresh}
        />
      </div>

      <ScrollArea className="flex-1" onScrollCapture={onScroll}>
        <div className="p-2">
          {accounts.map((item) => (
            <Card
              key={item.accountId}
              onClick={() => changeAccount(item)}
              className={cn(
                'mb-2 cursor-pointer p-3 transition-colors hover:bg-accent',
                currentAccountId === item.accountId && 'bg-accent',
              )}
            >
              <div className="mb-1 truncate text-sm">{item.email}</div>
              {item.perm && item.perm !== 'owner' && (
                <div className="mb-2 text-[11px] uppercase tracking-wide text-muted-foreground">
                  {permLabel(item.perm)}
                </div>
              )}
              <div className="flex items-center justify-between">
                <div onClick={(e) => e.stopPropagation()}>
                  <Icon
                    icon={item.allReceive ? 'flat-color-icons:folder' : 'eva:email-fill'}
                    width="22"
                    height="22"
                    className="cursor-pointer"
                    color={item.allReceive ? '#23c4f1' : '#fccb1a'}
                    onClick={() => toggleAllReceive(item)}
                  />
                </div>
                <div className="flex items-center gap-2" onClick={(e) => e.stopPropagation()}>
                  <Icon
                    icon="fluent-color:clipboard-24"
                    width="22"
                    height="22"
                    className="cursor-pointer"
                    onClick={() => copyAccount(item.email)}
                  />
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <span className="cursor-pointer">
                        <Icon
                          icon="fluent:settings-24-filled"
                          width="21"
                          height="21"
                          color="#909399"
                        />
                      </span>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      {canRename(item) && (
                        <DropdownMenuItem
                          onClick={() => {
                            setRenameTarget(item);
                            setRenameValue(item.name ?? '');
                          }}
                        >
                          {t('rename')}
                        </DropdownMenuItem>
                      )}
                      {item.accountId !== selfAccountId && (
                        <DropdownMenuItem onClick={() => setAsTop(item)}>
                          {t('pin')}
                        </DropdownMenuItem>
                      )}
                      {canManage(item) && (
                        <DropdownMenuItem onClick={() => setMemberTarget(item)}>
                          {t('memberManagement')}
                        </DropdownMenuItem>
                      )}
                      {item.perm === 'owner' && item.accountId !== selfAccountId && hasPerm('account:delete') && (
                        <DropdownMenuItem onClick={() => setDeleteTarget(item)}>
                          {t('delete')}
                        </DropdownMenuItem>
                      )}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </div>
            </Card>
          ))}
          {loading && (
            <div className="py-4 text-center text-sm text-muted-foreground">{t('loading')}</div>
          )}
        </div>
      </ScrollArea>

      <Dialog open={addOpen} onOpenChange={setAddOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('addAccount')}</DialogTitle>
          </DialogHeader>
          <Input
            value={addEmail}
            onChange={(e) => setAddEmail(e.target.value)}
            placeholder={t('email')}
          />
          <DialogFooter>
            <Button variant="outline" onClick={() => setAddOpen(false)}>
              {t('cancel')}
            </Button>
            <Button onClick={submitAdd}>{t('confirm')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={!!renameTarget} onOpenChange={(o) => !o && setRenameTarget(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('rename')}</DialogTitle>
          </DialogHeader>
          <Input value={renameValue} onChange={(e) => setRenameValue(e.target.value)} />
          <DialogFooter>
            <Button variant="outline" onClick={() => setRenameTarget(null)}>
              {t('cancel')}
            </Button>
            <Button onClick={submitRename}>{t('confirm')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <AlertDialog open={!!deleteTarget} onOpenChange={(o) => !o && setDeleteTarget(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('delete')}</AlertDialogTitle>
            <AlertDialogDescription>{deleteTarget?.email}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t('cancel')}</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete}>{t('confirm')}</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {memberTarget && (
        <AccountMemberDialog
          open={!!memberTarget}
          accountId={memberTarget.accountId}
          accountEmail={memberTarget.email}
          canManage={canManage(memberTarget)}
          onClose={() => setMemberTarget(null)}
        />
      )}
    </div>
  );
}
