// mail-vue/src/layout/aside/index.vue
<template>
  <el-scrollbar class="scroll">
    <div>
      <div class="title" >
        <Icon icon="mdi:email-outline" width="24" height="24" />
        <div>{{settingStore.settings.title}}</div>
      </div>
      <el-menu :collapse="false" text-color="#fff" active-text-color="#fff" style="margin-top: 10px">
        <el-menu-item @click="router.push({name: 'email'})" index="email"
                      :class="route.meta.name === 'email' ? 'choose-item' : ''">
          <Icon icon="hugeicons:mailbox-01" width="20" height="20" />
          <span class="menu-name" style="margin-left: 21px">{{$t('inbox')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'send'})" index="send" v-perm="'email:send'"
                      :class="route.meta.name === 'send' ? 'choose-item' : ''">
          <Icon icon="cil:send" width="20" height="20" />
          <span class="menu-name" style="margin-left: 21px">{{$t('sent')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'draft'})" index="draft" v-perm="'email:send'"
                      :class="route.meta.name === 'draft' ? 'choose-item' : ''">
          <Icon icon="ep:document" width="19" height="19" />
          <span class="menu-name" style="margin-left: 22px">{{$t('drafts')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'star'})" index="star"
                      :class="route.meta.name === 'star' ? 'choose-item' : ''">
          <Icon icon="solar:star-line-duotone" width="20" height="20" />
          <span class="menu-name" style="margin-left: 21px">{{$t('starred')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'setting'})" index="setting"
                      :class="route.meta.name === 'setting' ? 'choose-item' : ''">
          <Icon icon="fluent:settings-48-regular" width="20" height="20" />
          <span class="menu-name" style="margin-left: 21px">{{$t('settings')}}</span>
        </el-menu-item>
        <div class="manage-title" v-perm="['all-email:query','user:query','role:query','setting:query','analysis:query','reg-key:query','signature:query']">
          <div>{{$t('manage')}}</div>
        </div>
        <el-menu-item @click="router.push({name: 'analysis'})" index="analysis" v-perm="'analysis:query'"
                      :class="route.meta.name === 'analysis' ? 'choose-item' : ''">
          <Icon icon="fluent:data-pie-20-regular" width="24" height="24" />
          <span class="menu-name" style="margin-left: 18px">{{$t('analytics')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'user'})" index="setting" v-perm="'user:query'"
                      :class="route.meta.name === 'user' ? 'choose-item' : ''">
          <Icon icon="si:user-alt-2-line" width="20" height="20" />
          <span class="menu-name" style="margin-left: 21px">{{$t('allUsers')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'all-email'})" index="all-email" v-perm="'all-email:query'"
                      :class="route.meta.name === 'all-email' ? 'choose-item' : ''">
          <Icon icon="fluent:mail-list-28-regular" width="22" height="22" />
          <span class="menu-name" style="margin-left: 20px">{{$t('allMail')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'role'})" index="setting" v-perm="'role:query'"
                      :class="route.meta.name === 'role' ? 'choose-item' : ''">
          <Icon icon="fluent:lock-closed-16-regular" width="22" height="22" />
          <span class="menu-name" style="margin-left: 20px">{{$t('permissions')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'reg-key'})" index="reg-key" v-perm="'reg-key:query'"
                      :class="route.meta.name === 'reg-key' ? 'choose-item' : ''">
          <Icon icon="fluent:fingerprint-20-filled" width="22" height="22" />
          <span class="menu-name" style="margin-left: 20px">{{$t('inviteCode')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'signature'})" index="signature" v-perm="'signature:query'"
                      :class="route.meta.name === 'signature' ? 'choose-item' : ''">
          <Icon icon="fluent:signature-32-regular" width="22" height="22" />
          <span class="menu-name" style="margin-left: 20px">{{$t('signature')}}</span>
        </el-menu-item>
        <el-menu-item @click="router.push({name: 'sys-setting'})" index="sys-setting" v-perm="'setting:query'"
                      :class="route.meta.name === 'sys-setting' ? 'choose-item' : ''">
          <Icon icon="eos-icons:system-ok-outlined" width="18" height="18" style="margin-left: 2px" />
          <span class="menu-name" style="margin-left: 22px">{{$t('SystemSettings')}}</span>
        </el-menu-item>
      </el-menu>
    </div>
  </el-scrollbar>
</template>

<script setup>
import router from "@/router/index.js";
import { useRoute } from "vue-router";
import {Icon} from "@iconify/vue";
import {useSettingStore} from "@/store/setting.js";

const settingStore = useSettingStore();
const route = useRoute();

</script>

<style lang="scss" scoped>

.title {
  margin: 15px 10px;
  height: 45px;
  border-radius: 6px;
  display: flex;
  position: relative;
  font-size: 16px;
  font-weight: bold;
  align-items: center;
  justify-content: center;
  gap: 5px;
  color: #ffffff;
  background: linear-gradient(135deg, #1890ff, #3a80dd);
  transition: all 0.3s ease;
  max-width: 240px;
  padding: 0 10px;
  > div {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    max-width: calc(240px - 20px - 30px);
  }

  :deep(.el-icon) {
    flex-shrink: 0;
    font-size: 20px;
  }

  .user-right-icon {
    align-self: center;
    position: absolute;
    font-size: 12px;
    right: 8px;
    color: #ffffff;
  }

}


.manage-title {
  margin-top: 10px;
  padding-left: 20px;
  color: #fff;
}

.el-menu-item {
  margin: 5px 10px !important;
  border-radius: 6px;
  height: 36px;
  padding: 10px !important;
}

.choose-item {
  font-weight: bold;
  background: rgba(255, 255, 255, 0.08) !important;
  backdrop-filter: blur(4px);
}

@media (hover: hover) {
  .el-menu-item:hover {
    background: rgba(255, 255, 255, 0.08) !important;
  }
}

.menu-name {
  user-select: none;
}


:deep(.el-scrollbar__wrap--hidden-default ) {
  background: var(--aside-backgound) !important;
}

:deep(.el-menu-item) {
  background: var(--aside-backgound);
}

:deep(.el-menu) {
  background: var(--aside-backgound);
}

.el-menu {
  border-right: 0;
  width: 260px;
}

:deep(.el-divider__text) {
  background: var(--aside-backgound);
  color: #FFFFFF;
}

.scroll {

}
</style>

// mail-react/src/layouts/aside.tsx
import { Icon } from '@iconify/react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ScrollArea } from '@/components/ui/scroll-area';
import { useSettingStore } from '@/store/setting';
import { useUiStore } from '@/store/ui';
import { hasPerm } from '@/perm';
import { cn } from '@/lib/utils';

interface MenuItem {
  path: string;
  name: string;
  label: string;
  icon: string;
  iconSize?: number;
  perm?: string | string[];
}

const MAIN_MENU: MenuItem[] = [
  { path: '/inbox', name: 'email', label: 'inbox', icon: 'hugeicons:mailbox-01' },
  { path: '/sent', name: 'send', label: 'sent', icon: 'cil:send', perm: 'email:send' },
  { path: '/drafts', name: 'draft', label: 'drafts', icon: 'ep:document', perm: 'email:send' },
  { path: '/starred', name: 'star', label: 'starred', icon: 'solar:star-line-duotone' },
  { path: '/settings', name: 'setting', label: 'settings', icon: 'fluent:settings-48-regular' },
];

const MANAGE_PERMS = [
  'all-email:query',
  'user:query',
  'role:query',
  'setting:query',
  'analysis:query',
  'reg-key:query',
  'signature:query',
];

const MANAGE_MENU: MenuItem[] = [
  { path: '/analysis', name: 'analysis', label: 'analytics', icon: 'fluent:data-pie-20-regular', iconSize: 22, perm: 'analysis:query' },
  { path: '/all-users', name: 'user', label: 'allUsers', icon: 'si:user-alt-2-line', perm: 'user:query' },
  { path: '/all-mail', name: 'all-email', label: 'allMail', icon: 'fluent:mail-list-28-regular', iconSize: 21, perm: 'all-email:query' },
  { path: '/role', name: 'role', label: 'permissions', icon: 'fluent:lock-closed-16-regular', iconSize: 21, perm: 'role:query' },
  { path: '/invite-code', name: 'reg-key', label: 'inviteCode', icon: 'fluent:fingerprint-20-filled', iconSize: 21, perm: 'reg-key:query' },
  { path: '/signatures', name: 'signature', label: 'signature', icon: 'fluent:signature-32-regular', iconSize: 21, perm: 'signature:query' },
  { path: '/system-setting', name: 'sys-setting', label: 'SystemSettings', icon: 'eos-icons:system-ok-outlined', iconSize: 18, perm: 'setting:query' },
];

export default function Aside() {
  const settings = useSettingStore((s) => s.settings);
  const navigate = useNavigate();
  const location = useLocation();
  const { t } = useTranslation();
  const isMobile = typeof window !== 'undefined' && window.innerWidth < 1025;
  const setAsideShow = useUiStore((s) => s.setAsideShow);

  function go(path: string) {
    navigate(path);
    if (isMobile) setAsideShow(false);
  }

  function renderItem(item: MenuItem) {
    if (item.perm && !hasPerm(item.perm)) return null;
    const active = location.pathname === item.path;
    return (
      <button
        key={item.path}
        type="button"
        onClick={() => go(item.path)}
        className={cn(
          'group mx-2 my-[1px] flex h-8 w-[calc(100%-1rem)] cursor-pointer items-center gap-2.5 rounded-md px-2.5 text-[13px] transition-colors duration-120 ease-expo',
          'text-muted-foreground hover:bg-accent hover:text-foreground',
          active && 'bg-accent text-foreground font-medium',
        )}
      >
        <Icon
          icon={item.icon}
          width={item.iconSize ?? 18}
          height={item.iconSize ?? 18}
          className={cn('shrink-0 transition-colors duration-120', active ? 'text-foreground' : 'text-muted-foreground/70 group-hover:text-foreground')}
        />
        <span className="select-none truncate">{t(item.label)}</span>
        {active && <span className="ml-auto h-1 w-1 rounded-full bg-brand" aria-hidden />}
      </button>
    );
  }

  return (
    <ScrollArea className="h-full w-[240px] border-r border-border bg-background">
      <div className="flex flex-col gap-1 px-2 pb-4 pt-4">
        <button
          type="button"
          onClick={() => go('/inbox')}
          className="mx-2 mb-3 flex h-9 items-center gap-2 rounded-md px-2 text-left transition-colors duration-120 hover:bg-accent"
        >
          <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-foreground text-background">
            <Icon icon="mdi:email-fast-outline" width="14" height="14" />
          </span>
          <span className="truncate text-[13px] font-semibold tracking-tight text-foreground">
            {settings?.title || 'Cloud Mail'}
          </span>
        </button>

        <nav className="flex flex-col gap-0">
          {MAIN_MENU.map(renderItem)}
        </nav>

        {hasPerm(MANAGE_PERMS) && (
          <>
            <div className="mx-3 mt-4 mb-1 text-eyebrow">{t('manage')}</div>
            <nav className="flex flex-col gap-0">{MANAGE_MENU.map(renderItem)}</nav>
          </>
        )}
      </div>
    </ScrollArea>
  );
}
