// mail-vue/src/layout/write/index.vue
<template>
  <div class="send" v-show="show">
    <div class="write-box">
      <div class="title">
        <div class="title-left">
          <span class="title-text">
            <Icon icon="hugeicons:quill-write-01" width="28" height="28"/>
          </span>
          <span class="sender">{{ $t('sender') }}:</span>
          <span class="sender-name">{{ form.name }}</span>
          <span class="send-email"><{{ form.sendEmail }}></span>
        </div>
        <div @click="close" style="cursor: pointer;">
          <Icon icon="material-symbols-light:close-rounded" width="22" height="22"/>
        </div>
      </div>
      <div class="container">
        <el-input-tag  @add-tag="(val) => addTagChange(val, form.receiveEmail)" tag-type="primary" @input="(val) => inputChange(val, form.receiveEmail)" @focus="activeTagField = 'to'" size="default" v-model="form.receiveEmail" >
          <template #prefix>
            <div class="item-title" >{{ $t('recipient') }}</div>
            <el-select
                ref="recipientSelect"
                class="write-select"
                popper-class="write-select"
                :show-arrow="false"
                :no-match-text="' '"
                :no-data-text="' '"
                @visible-change="selectStatusChange"
                @change="(v) => selectChange(v, form.receiveEmail)"
            >
              <el-option
                  v-for="item in selectRecipientList"
                  :key="item"
                  :label="item"
                  :value="item"
                  style="color: #999896;"
              />
            </el-select>
          </template>
          <template #suffix>
            <div class="suffix-row">
              <a class="cc-bcc-link" :class="{active: showCc}" @click.stop="toggleCc">{{ t('cc') }}</a>
              <a class="cc-bcc-link" :class="{active: showBcc}" @click.stop="toggleBcc">{{ t('bcc') }}</a>
              <Icon icon="fa7-solid:user-plus" width="20" height="20" class="add-contact" @click.stop="openContacts" />
            </div>
          </template>
        </el-input-tag>
        <el-input-tag
            v-if="showCc"
            @add-tag="(val) => addTagChange(val, form.cc)"
            tag-type="info"
            @input="(val) => inputChange(val, form.cc)"
            @focus="activeTagField = 'cc'"
            size="default"
            v-model="form.cc"
        >
          <template #prefix>
            <div class="item-title">{{ t('cc') }}</div>
            <el-select
                ref="ccSelect"
                class="write-select"
                popper-class="write-select"
                :show-arrow="false"
                :no-match-text="' '"
                :no-data-text="' '"
                @visible-change="selectStatusChange"
                @change="(v) => selectChange(v, form.cc)"
            >
              <el-option
                  v-for="item in selectRecipientList"
                  :key="item"
                  :label="item"
                  :value="item"
                  style="color: #999896;"
              />
            </el-select>
          </template>
        </el-input-tag>
        <el-input-tag
            v-if="showBcc"
            @add-tag="(val) => addTagChange(val, form.bcc)"
            tag-type="warning"
            @input="(val) => inputChange(val, form.bcc)"
            @focus="activeTagField = 'bcc'"
            size="default"
            v-model="form.bcc"
        >
          <template #prefix>
            <div class="item-title">{{ t('bcc') }}</div>
            <el-select
                ref="bccSelect"
                class="write-select"
                popper-class="write-select"
                :show-arrow="false"
                :no-match-text="' '"
                :no-data-text="' '"
                @visible-change="selectStatusChange"
                @change="(v) => selectChange(v, form.bcc)"
            >
              <el-option
                  v-for="item in selectRecipientList"
                  :key="item"
                  :label="item"
                  :value="item"
                style="color: #999896;"
              />
            </el-select>
          </template>
        </el-input-tag>
        <el-input v-model="form.subject" :placeholder="t('subject')" />
        <tinyEditor :def-value="defValue" ref="editor" @change="change" @focus="focusChange" />
        <div class="button-item">
          <div class="att-add" @click="chooseFile">
            <Icon icon="iconamoon:attachment-fill" width="24" height="24"/>
          </div>
          <div class="att-clear" @click="clearContent">
            <Icon icon="icon-park-outline:clear-format" width="24" height="24 "/>
          </div>
          <div class="signature-check">
            <el-checkbox v-model="form.includeSignature">{{ t('includeSignature') }}</el-checkbox>
          </div>
          <div class="att-list">
            <div class="att-item" v-for="(item,index) in form.attachments" :key="index">
              <Icon v-bind="getIconByName(item.filename)"/>
              <span class="att-filename">{{ item.filename }}</span>
              <span class="att-size">{{ formatBytes(item.size) }}</span>
              <Icon style="cursor: pointer;" icon="material-symbols-light:close-rounded" @click="delAtt(index)"
                    width="22" height="22"/>
            </div>
          </div>
          <div class="send-actions">
            <el-button @click="openPreview">{{ $t('preview') }}</el-button>
            <el-button type="primary" @click="sendEmail" v-if="form.sendType === 'reply'">{{ $t('reply') }}</el-button>
            <el-button type="primary" @click="sendEmail" v-else-if="form.sendType === 'forward'">{{ $t('forward') }}</el-button>
            <el-button type="primary" @click="sendEmail" v-else>{{ $t('send') }}</el-button>
          </div>
        </div>
      </div>
    </div>
    <el-dialog top="10vh" v-model="showContacts" @closed="clearSelectContact" :title="t('recentContacts')">
      <el-table ref="contactsTabRef" row-key="email" :data="contacts" style="height: 445px">
        <el-table-column type="selection" width="32" />
        <el-table-column property="email" :label="t('emailAccount')" >
          <template #default="props">
            <div class="email-row">{{ props.row.email }}</div>
          </template>
        </el-table-column>
        <el-table-column width="55" label="" >
          <template #default>
            <div style="display: flex;">
              <Icon icon="mage:user" style="color: var(--el-text-color-primary)" width="22" height="22" color="#606266" />
            </div>
          </template>
        </el-table-column>
      </el-table>
      <div class="contacts-bottom">
        <el-button type="default" @click="deleteContact">{{t('clear')}}</el-button>
        <el-button type="primary" @click="chooseContact">{{t('selectContacts')}}</el-button>
      </div>
    </el-dialog>
    <el-dialog class="preview-dialog" top="8vh" v-model="previewShow" :title="t('signaturePreview')">
      <div class="preview-box">
        <shadowHtml :html="previewHtml"/>
      </div>
    </el-dialog>
  </div>
</template>
<script setup>
import tinyEditor from '@/components/tiny-editor/index.vue'
import shadowHtml from '@/components/shadow-html/index.vue'
import {h, nextTick, onMounted, onUnmounted, reactive, ref, toRaw, computed, watch} from "vue";
import {Icon} from "@iconify/vue";
import {useUserStore} from "@/store/user.js";
import {emailSend} from "@/request/email.js";
import {isEmail} from "@/utils/verify-utils.js";
import {useAccountStore} from "@/store/account.js";
import {useEmailStore} from "@/store/email.js";
import {fileToBase64, formatBytes} from "@/utils/file-utils.js";
import {getIconByName} from "@/utils/icon-utils.js";
import sendPercent from "@/components/send-percent/index.vue"
import {toOssDomain} from "@/utils/convert.js";
import {formatDetailDate} from "@/utils/day.js";
import {useSettingStore} from "@/store/setting.js";
import {userDraftStore} from "@/store/draft.js";
import {useWriterStore} from "@/store/writer.js";
import db from "@/db/db.js";
import dayjs from "dayjs";
import {useI18n} from "vue-i18n";
import router from "@/router/index.js";
import {ElMessageBox} from "element-plus";
import {signatureGet} from "@/request/signature.js";
import {useSignatureStore} from "@/store/signature.js";

defineExpose({
  open,
  openReply,
  openForward,
  openDraft
})

const {t} = useI18n()
const writerStore = useWriterStore();
const draftStore = userDraftStore()
const settingStore = useSettingStore()
const signatureStore = useSignatureStore()
const emailStore = useEmailStore();
const accountStore = useAccountStore()
const editor = ref({})
const userStore = useUserStore();
const show = ref(false);
const percent = ref(0)
let percentMessage = null
let sending = false
const defValue = ref('')
const contactsTabRef = ref({})
const showContacts = ref(false)
const previewShow = ref(false)
const previewSignature = ref('')
const recipientSelect = ref()
const ccSelect = ref()
const bccSelect = ref()
let selectStatus = false
let previewSignatureReq = 0
const backReply = reactive({
  receiveEmail: [],
  cc: [],
  bcc: [],
  subject: '',
  content: '',
  sendType: ''
})
const form = reactive({
  sendEmail: '',
  receiveEmail: [],
  cc: [],
  bcc: [],
  accountId: -1,
  name: '',
  subject: '',
  content: '',
  sendType: '',
  text: '',
  includeSignature: true,
  emailId: 0,
  attachments: [],
  draftId: null,
})

const showCc = ref(false)
const showBcc = ref(false)
const activeTagField = ref('to')

const selectRecipientList = ref([])

const contacts = computed(() => writerStore.sendRecipientRecord.map(item => ({email: item})))

const previewHtml = computed(() => {
  const content = form.content || ''
  const signature = form.includeSignature && previewSignature.value
      ? `
        <div class="cloud-mail-signature" data-cloud-mail-signature="true" style="margin-top:16px;">
          ${previewSignature.value}
        </div>
      `
      : ''

  return formatImage(`${content}${signature}`)
})

watch(
    () => [previewShow.value, form.includeSignature, form.sendEmail, signatureStore.refresh],
    () => {
      if (previewShow.value) {
        refreshPreviewSignature()
      }
    }
)

function openContacts() {
  showContacts.value = true
  nextTick(() => {
    form.receiveEmail.forEach(item => {
      if (writerStore.sendRecipientRecord.includes(item)) {
        contactsTabRef.value.toggleRowSelection({email: item});
      }
    })
  })
}

function deleteContact() {
  ElMessageBox.confirm(t('confirmDeletionOfContacts'), {
    confirmButtonText: t('confirm'),
    cancelButtonText: t('cancel'),
    type: 'warning'
  }).then(() => {
    const contactList = contactsTabRef.value.getSelectionRows().map(item => item.email);
    form.receiveEmail = form.receiveEmail.filter(item => !contactList.includes(item));
    writerStore.sendRecipientRecord = writerStore.sendRecipientRecord.filter(item => !contactList.includes(item));
  })
}

function chooseContact() {

  const contactList = contactsTabRef.value.getSelectionRows().map(item => item.email);
  contactList.forEach(item => {
    if (!form.receiveEmail.includes(item)) {
      form.receiveEmail.push(item);
    }
  })

  form.receiveEmail = form.receiveEmail.filter(item => {
    return contactList.includes(item) || !writerStore.sendRecipientRecord.includes(item);
  });

  showContacts.value = false
}

function clearSelectContact() {
  contactsTabRef.value.clearSelection();
}

function selectChange(value, model) {
  if (!model.includes(value)) {
    model.push(value)
  }
}

function selectStatusChange(status) {
  selectStatus = status
}

const openSelect = () => {
  const target = activeTagField.value === 'cc' ? ccSelect.value
      : activeTagField.value === 'bcc' ? bccSelect.value
          : recipientSelect.value
  if (target && target.toggleMenu) target.toggleMenu()
}

function inputChange(value, model) {

  const exclude = new Set([...form.receiveEmail, ...form.cc, ...form.bcc])
  selectRecipientList.value = writerStore.sendRecipientRecord.filter(item => value && !exclude.has(item) && item.startsWith(value)).slice(0, 10);

  if (!selectStatus && selectRecipientList.value.length > 0) {
    openSelect()
  }

  if (selectStatus && selectRecipientList.value.length === 0) {
    openSelect()
  }

}

function addTagChange(val, model) {

  const emails = Array.from(new Set(
      val.split(/[,，]/).map(item => item.trim()).filter(item => item)
  ));

  model.splice(model.length - 1, 1)

  let has = false
  emails.forEach(email => {
    if (isEmail(email) && !model.includes(email)) {
      model.push(email)
      has = true
    }
  })
  if (selectStatus && has) openSelect()
}

function toggleCc() {
  showCc.value = !showCc.value
  if (!showCc.value) form.cc = []
}

function toggleBcc() {
  showBcc.value = !showBcc.value
  if (!showBcc.value) form.bcc = []
}

function clearContent() {
  ElMessageBox.confirm(t('clearContentConfirm'), {
    confirmButtonText: t('confirm'),
    cancelButtonText: t('cancel'),
    type: 'warning'
  }).then(() => {
    resetForm()
  })

}

function delAtt(index) {
  form.attachments.splice(index, 1);
}

async function openPreview() {
  form.content = editor.value.getContent();
  previewShow.value = true;
  await refreshPreviewSignature();
}

async function refreshPreviewSignature() {
  const req = ++previewSignatureReq
  previewSignature.value = ''

  if (form.includeSignature && form.sendEmail) {
    try {
      const signature = await signatureGet(form.sendEmail);
      if (req !== previewSignatureReq) return
      previewSignature.value = signature.content || ''
    } catch (e) {
      if (req !== previewSignatureReq) return
      previewSignature.value = ''
    }
  }
}

function chooseFile() {
  const doc = document.createElement("input")
  doc.setAttribute("type", "file")
  doc.multiple = true;
  doc.click()
  doc.onchange = async (e) => {

    const fileList = e.target.files;

    for (const file of fileList) {

      const size = file.size
      const filename = file.name
      const contentType = file.type

      const content = await fileToBase64(file)
      form.attachments.push({content, filename, size, contentType})

    }

  }
}

async function sendEmail() {

  if (form.receiveEmail.length === 0) {
    ElMessage({
      message: t('emptyRecipientMsg'),
      type: 'error',
      plain: true,
    })
    return
  }

  if (!form.subject) {
    ElMessage({
      message: t('emptySubjectMsg'),
      type: 'error',
      plain: true,
    })
    return
  }

  if (!form.content) {
    form.content = editor.value.getContent();
  }

  if (!form.content) {
    ElMessage({
      message: t('emptyContentMsg'),
      type: 'error',
      plain: true,
    })
    return
  }

  if (form.manyType === 'divide' && form.attachments.length > 0) {
    ElMessage({
      message: t('noSeparateSendMsg'),
      type: 'error',
      plain: true,
    })
    return
  }

  if (sending) {
    ElMessage({
      message: t('sendingErrorMsg'),
      type: 'error',
      plain: true,
    })
    return
  }

  percentMessage = ElMessage({
    message: () => h(sendPercent, {value: percent.value, desc: t('sending')}),
    dangerouslyUseHTMLString: true,
    plain: true,
    duration: 0,
    customClass: 'message-bottom'
  })

  sending = true

  show.value = false

  emailSend(form, (e) => {
    percent.value = Math.round((e.loaded * 98) / e.total)
  }).then(emailList => {
    const email = emailList[0]
    emailList.forEach(item => {
      emailStore.sendScroll?.addItem(item)
    })

    ElNotification({
      title: t('sendSuccessMsg'),
      type: "success",
      message: h('span', {style: 'color: teal'}, email.subject),
      position: 'bottom-right'
    })

    userStore.refreshUserInfo();

    addRecipientRecord();

    if (form.draftId) {
      form.subject = ''
      form.content = ''
      form.receiveEmail = []
      draftStore.setDraft = {...toRaw(form)}
    }

    show.value = false
    resetForm();
  }).catch((e) => {
    if (Array.isArray(e?.data)) {
      e.data.forEach(item => emailStore.sendScroll?.addItem(item))
    }
    ElNotification({
      title: t('sendFailMsg'),
      type: e.code === 403 ? 'warning' : 'error',
      message: h('span', {style: 'color: teal'}, e.message),
      position: 'bottom-right'
    })
    if (e.code === 401) {
      localStorage.removeItem('token');
      router.replace('/login');
    }
    show.value = true
    addRecipientRecord();
  }).finally(() => {
    percentMessage.close()
    percent.value = 0
    sending = false
  })
}

function addRecipientRecord() {
  const all = [...form.receiveEmail, ...form.cc, ...form.bcc];
  writerStore.sendRecipientRecord = writerStore.sendRecipientRecord.filter(
      email => !all.includes(email)
  );

  writerStore.sendRecipientRecord.unshift(...all);
  writerStore.sendRecipientRecord = writerStore.sendRecipientRecord.slice(0, 500);
}

function resetForm() {
  form.receiveEmail = []
  form.cc = []
  form.bcc = []
  form.subject = ''
  form.content = ''
  form.manyType = null
  form.includeSignature = true
  form.attachments = []
  form.sendType = ''
  form.emailId = 0
  form.draftId = null
  showCc.value = false
  showBcc.value = false
  backReply.content = ''
  backReply.subject = ''
  backReply.receiveEmail = []
  backReply.sendType = ''
  editor.value.clearEditor()
}

function change(content, text) {
  form.content = content;
  form.text = text
}

function focusChange() {
  if (selectStatus) openSelect()
}

function openForward(email) {
  resetForm();

  email.subject = email.subject || ''

  form.subject = email.subject
  form.sendType = 'forward'

  defValue.value = ''

  setTimeout(() => {
    const forwardFrom = email.sendEmail
    const forwardFromName = email.name || ''
    const forwardDate = formatDetailDate(email.createTime)
    const forwardSubject = email.subject
    let forwardTo = ''
    try {
      const recipients = JSON.parse(email.recipient || '[]')
      if (Array.isArray(recipients) && recipients.length > 0) {
        forwardTo = recipients.map(r => r.address).join(', ')
      }
    } catch (_) {}
    const body = formatImage(email.content) || `<pre style="font-family: inherit;word-break: break-word;white-space: pre-wrap;margin: 0">${email.text}</pre>`

    defValue.value = `
      <div></div>
      <div>
      <br>
          ---------- Forwarded message ----------<br>
          From: ${forwardFromName ? `${forwardFromName} &lt;${forwardFrom}&gt;` : forwardFrom}<br>
          Date: ${forwardDate}<br>
          Subject: ${forwardSubject}<br>
          ${forwardTo ? `To: ${forwardTo}<br>` : ''}
      </div>
      <blockquote class="mceNonEditable cmq-reply-quote" style="margin: 0 0 0 0.8ex;border-left: 1px solid rgb(204,204,204);padding-left: 1ex;">
        <article>
            ${body}
        </article>
      </blockquote>`
    open()

    nextTick(() => {
      backReply.content = editor.value.getContent()
      backReply.subject = form.subject
      backReply.receiveEmail = form.receiveEmail
      backReply.sendType = form.sendType
    })

  });
}

function openReply(email) {

  resetForm();

  email.subject = email.subject || ''

  form.receiveEmail.push(email.sendEmail)
  form.subject = (
      email.subject.startsWith('Re:') ||
      email.subject.startsWith('Re：') ||
      email.subject.startsWith('回复：') ||
      email.subject.startsWith('回复:')) ? email.subject : 'Re: ' + email.subject
  form.sendType = 'reply'
  form.emailId = email.emailId

  defValue.value = ''

  setTimeout(() => {
    defValue.value = `
    <div></div>
    <div>
    <br>
        ${formatDetailDate(email.createTime)} ${email.name} &lt${email.sendEmail}&gt ${t('wrote')}:
    </div>
    <blockquote class="mceNonEditable cmq-reply-quote" style="margin: 0 0 0 0.8ex;border-left: 1px solid rgb(204,204,204);padding-left: 1ex;">
      <article>
          ${formatImage(email.content) || `<pre style="font-family: inherit;word-break: break-word;white-space: pre-wrap;margin: 0">${email.text}</pre>`}
      </article>
    </blockquote>`
    open()

    nextTick(() => {
      backReply.content = editor.value.getContent()
      backReply.subject = form.subject
      backReply.receiveEmail = form.receiveEmail
      backReply.sendType = form.sendType
    })
  })

}

function formatImage(content) {
  content = content || '';
  const domain = settingStore.settings.r2Domain;
  return content.replace(/{{domain}}/g, toOssDomain(domain) + '/');
}

function open() {
  if (!accountStore.currentAccount.email) {
    form.sendEmail = userStore.user.email;
    form.accountId = userStore.user.account.accountId;
    form.name = userStore.user.name;
  } else {
    form.sendEmail = accountStore.currentAccount.email;
    form.accountId = accountStore.currentAccount.accountId;
    form.name = accountStore.currentAccount.name;
  }
  show.value = true;
  editor.value.focus()
}

function openDraft(draft) {
  Object.assign(form, {...draft})
  form.includeSignature = draft.includeSignature ?? true
  form.cc = Array.isArray(draft.cc) ? draft.cc : []
  form.bcc = Array.isArray(draft.bcc) ? draft.bcc : []
  showCc.value = form.cc.length > 0
  showBcc.value = form.bcc.length > 0
  defValue.value = ''
  setTimeout(() => defValue.value = form.content)
  show.value = true;
  editor.value.focus()
}

const handleKeyDown = (event) => {
  if (event.key === 'Escape') {
    close()
  }
};

onMounted(() => {
  window.addEventListener('keydown', handleKeyDown);
});

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeyDown);
});

function close() {

  if (selectStatus) openSelect();

  if (!form.content) {
    form.content = editor.value.getContent();
  }

  if (form.draftId) {
    draftStore.setDraft = {...toRaw(form)}
    show.value = false
    resetForm()
    return;
  }

  if (!(form.content || form.subject || form.receiveEmail.length > 0 || form.cc.length > 0 || form.bcc.length > 0)) {
    show.value = false
    resetForm()
    return;
  }

  if (backReply.sendType === 'reply' || backReply.sendType === 'forward') {
    let subjectFlag = form.subject === backReply.subject
    let contentFlag = editor.value.getContent() === backReply.content
    let receiveFlag = form.receiveEmail.length === 1 && form.receiveEmail[0] === backReply.receiveEmail[0]
    if (backReply.sendType === 'forward' && form.receiveEmail.length === 0) {
      receiveFlag = true;
    }
    let ccFlag = (form.cc || []).length === (backReply.cc || []).length && (form.cc || []).every((v, i) => v === backReply.cc[i])
    let bccFlag = (form.bcc || []).length === (backReply.bcc || []).length && (form.bcc || []).every((v, i) => v === backReply.bcc[i])
    if (subjectFlag && contentFlag && receiveFlag && ccFlag && bccFlag) {
      resetForm();
      close()
      return;
    }
  }

  ElMessageBox.confirm(t('saveDraftConfirm'), {
    confirmButtonText: t('confirm'),
    cancelButtonText: t('cancel'),
    type: 'warning',
    distinguishCancelAndClose: true
  }).then(async () => {
    const formData = {...toRaw(form)};
    delete formData.draftId
    delete formData.attachments
    formData.createTime = dayjs().utc().format('YYYY-MM-DD HH:mm:ss');
    const draftId = await db.value.draft.add({...formData})
    db.value.att.add({draftId, attachments: toRaw(form.attachments)})
    draftStore.refreshList++
    show.value = false
    await nextTick(() => {
      resetForm()
    })
  }).catch((action) => {
    if (action === 'cancel') {
      show.value = false
      resetForm()
    }
  })

}

</script>
<style>
.write-select .el-select-dropdown__list {
  padding: 4px 4px !important;
}
.write-select .el-select-dropdown__item {
  padding: 0 10px 0 10px;
}

.write-select .el-select-dropdown {
  min-width: 0 !important;
}
</style>
<style scoped lang="scss">
.send {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;

  .write-box {
    background: var(--el-bg-color);
    width: min(1367px, calc(100% - 80px));
    box-shadow: var(--el-box-shadow-light);
    border: 1px solid var(--el-border-color-light);
    transition: var(--el-transition-duration);
    padding: 15px;
    border-radius: 8px;
    display: grid;
    grid-template-rows: auto 1fr;
    overflow: hidden;
    @media (max-width: 1024px) and (max-height: 699px) {
      width: 100%;
      height: 100%;
      border-radius: 0;
      border: 0;
      padding-top: 10px;
    }

    @media (min-width: 1025px) and (max-height: 700px) {
      height: min(800px, calc(100vh - 60px));
    }

    .title {
      display: flex;
      justify-content: space-between;
      margin-bottom: 10px;

      .title-left {
        align-items: center;
        display: grid;
        grid-template-columns: auto auto auto 1fr;
      }

      .title-text {
      }

      .sender {
        margin-left: 8px;
      }

      .sender-name {
        margin-left: 8px;
        font-weight: bold;
      }

      .send-email {
        color: #999896;
        margin-left: 5px;
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
      }


      div {
        display: flex;
        align-items: center;
      }
    }

    .container {
      height: 100%;
      display: grid;
      grid-template-rows: auto auto auto auto 1fr auto;
      gap: 15px;

      .item-title {
      }

      .button-item {
        display: grid;
        grid-template-columns: auto auto auto 1fr auto;
        align-items: center;

        @media (max-width: 767px) {
          grid-template-columns: auto auto 1fr;
          gap: 8px;

          .att-list {
            grid-column: 1 / -1;
            order: 2;
            padding-left: 0;
            padding-right: 0;
          }

          .send-actions {
            grid-column: 1 / -1;
            justify-content: flex-end;
            order: 3;
          }
        }

        .att-add {
          cursor: pointer;
        }

        .att-clear {
          cursor: pointer;
          margin-left: 10px;
        }

        .signature-check {
          margin-left: 12px;
          white-space: nowrap;
        }

        .att-list {
          display: grid;
          gap: 5px;
          grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
          padding-left: 10px;
          padding-right: 10px;
          max-height: 110px;
          overflow-y: auto;
          @media (max-width: 450px) {
            grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
          }

          .att-item {
            display: grid;
            grid-template-columns: auto 1fr auto auto;
            gap: 5px;
            height: 32px;
            font-size: 14px;
            padding: 4px 5px;
            background: var(--light-ill);
            border-radius: 4px;
            .att-filename {
              white-space: nowrap;
              text-overflow: ellipsis;
              overflow: hidden;
            }
          }
        }

        .send-actions {
          display: flex;
          align-items: center;
          gap: 8px;
          white-space: nowrap;
        }
      }
    }
  }

}

.preview-box {
  height: min(620px, calc(82vh - 120px));
  border: 1px solid var(--el-border-color-light);
  border-radius: 6px;
  padding: 12px;
  overflow: auto;
}

.email-row {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

:deep(.el-dialog) {
  width: 420px !important;
  @media (max-width: 460px) {
    width: calc(100% - 40px) !important;
    margin-right: 20px !important;
    margin-left: 20px !important;
  }
}

:deep(.preview-dialog) {
  width: min(860px, calc(100% - 40px)) !important;
}

.contacts-bottom {
  display: flex;
  justify-content: end;
  margin-top: 10px;
}

.add-contact {
  color: var(--regular-text-color)
}

.suffix-row {
  display: flex;
  align-items: center;
  margin-right: 3px;
  gap: 6px;
}

.cc-bcc-link {
  font-size: 13px;
  color: var(--el-color-primary);
  cursor: pointer;
  user-select: none;
  padding: 0 2px;
  border-radius: 3px;
}

.cc-bcc-link:hover {
  text-decoration: underline;
}

.cc-bcc-link.active {
  color: var(--el-color-primary);
  font-weight: 600;
}

.write-select {
  position: absolute;
  width: 300px;
  left: 60px;
  z-index: 0;
  opacity: 0;
  pointer-events: none;
}

:deep(.el-input-tag__suffix) {
  padding-right: 4px;
}

.icon {
  cursor: pointer;
}
</style>

// mail-react/src/layouts/write.tsx
import { useEffect, useRef, useState } from 'react';
import { Icon } from '@iconify/react';
import { toast } from 'sonner';
import { useTranslation } from 'react-i18next';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from '@/components/ui/sheet';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import HtmlEditor, { type HtmlEditorHandle } from '@/components/tiptap-editor';
import SendPercent from '@/components/send-percent';
import ShadowHtml from '@/components/shadow-html';
import { useUiStore } from '@/store/ui';
import { useUserStore } from '@/store/user';
import { useAccountStore } from '@/store/account';
import { useEmailStore } from '@/store/email';
import { useDraftStore } from '@/store/draft';
import { useWriterStore } from '@/store/writer';
import { useSignatureStore } from '@/store/signature';
import { useSettingStore } from '@/store/setting';
import { emailSend } from '@/request/email';
import { signatureGet } from '@/request/signature';
import { isEmail } from '@/utils/verify-utils';
import { fileToBase64, formatBytes } from '@/utils/file-utils';
import { getIconByName } from '@/utils/icon-utils';

// Per-file and total attachment caps. Generous enough for typical mail but
// small enough that a single accidental video upload doesn't blow the request.
const MAX_ATTACHMENT_SIZE = 25 * 1024 * 1024; // 25 MB per file
const MAX_TOTAL_ATTACHMENT_SIZE = 50 * 1024 * 1024; // 50 MB across all files
import { formatDetailDate } from '@/utils/day';
import { toOssDomain } from '@/utils/convert';
import { getDB, type DraftRecord } from '@/db/db';
import { hasPerm } from '@/perm';
import { setToken } from '@/request/http';

interface WriteForm {
  sendEmail: string;
  receiveEmail: string[];
  accountId: number;
  name: string;
  subject: string;
  content: string;
  text: string;
  sendType: '' | 'reply' | 'forward';
  includeSignature: boolean;
  emailId: number;
  draftId: number | null;
  attachments: Attachment[];
}

interface Attachment {
  filename: string;
  size: number;
  content: string;
  contentType: string;
}

const initialForm: WriteForm = {
  sendEmail: '',
  receiveEmail: [],
  accountId: -1,
  name: '',
  subject: '',
  content: '',
  text: '',
  sendType: '',
  includeSignature: true,
  emailId: 0,
  draftId: null,
  attachments: [],
};

export default function Writer() {
  const { t } = useTranslation();
  const writerShow = useUiStore((s) => s.writerShow);
  const writerData = useUiStore((s) => s.writerData);
  const closeWriter = useUiStore((s) => s.closeWriter);
  const refreshUserInfo = useUserStore((s) => s.refreshUserInfo);
  const account = useAccountStore();
  const userStore = useUserStore();
  const emailStore = useEmailStore();
  const setDraftInStore = useDraftStore((s) => s.setSetDraft);
  const writerStore = useWriterStore();
  const signatureStore = useSignatureStore();
  const settings = useSettingStore((s) => s.settings);
  const editorRef = useRef<HtmlEditorHandle>(null);
  const [form, setForm] = useState<WriteForm>(initialForm);
  const [confirmClose, setConfirmClose] = useState(false);
  const [percent, setPercent] = useState(0);
  const [recipientInput, setRecipientInput] = useState('');
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [previewSignature, setPreviewSignature] = useState('');
  const recipientInputRef = useRef<HTMLInputElement>(null);
  const previewReqRef = useRef(0);

  // Sync open state with store data
  useEffect(() => {
    if (!writerShow) return;
    if (writerData?.replyTo) {
      openReply(writerData.replyTo);
    } else if (writerData?.forwardFrom) {
      openForward(writerData.forwardFrom);
    } else if (writerData && writerData.draftId) {
      openDraft(writerData);
    } else {
      openNew();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [writerShow]);

  function openNew() {
    const currentAccountEmail = account.currentAccount?.email;
    const currentAccountId = account.currentAccountId;
    const user = userStore.user;
    if (!currentAccountEmail && user) {
      setForm({
        ...initialForm,
        sendEmail: user.email,
        accountId: user.account?.accountId ?? -1,
        name: user.name,
      });
    } else if (account.currentAccount) {
      setForm({
        ...initialForm,
        sendEmail: currentAccountEmail ?? '',
        accountId: currentAccountId,
        name: account.currentAccount.name ?? '',
      });
    }
    setTimeout(() => editorRef.current?.focus());
  }

  function openReply(email: any) {
    resetForm();
    const subject =
      email.subject?.startsWith('Re:') ||
      email.subject?.startsWith('Re：') ||
      email.subject?.startsWith('回复：') ||
      email.subject?.startsWith('回复:')
        ? email.subject
        : 'Re: ' + (email.subject || '');
    setForm((f) => ({
      ...f,
      receiveEmail: [email.sendEmail],
      subject,
      sendType: 'reply',
      emailId: email.emailId,
    }));
    const body = `<br><div>${
      formatDetailDate(email.createTime)
    } ${email.name} &lt;${email.sendEmail}&gt; ${t('wrote')}:</div><blockquote style="margin: 0 0 0 0.8ex;border-left: 1px solid #ccc;padding-left: 1ex;">${
      formatImage(email.content) || `<pre style="font-family:inherit;word-break:break-word;white-space:pre-wrap;margin:0">${email.text}</pre>`
    }</blockquote>`;
    setTimeout(() => {
      editorRef.current?.focus();
      setForm((f) => ({ ...f, content: body, text: email.text || '' }));
    }, 0);
  }

  function openForward(email: any) {
    resetForm();
    setForm((f) => ({
      ...f,
      subject: email.subject || '',
      sendType: 'forward',
    }));
    const body =
      formatImage(email.content) ||
      `<pre style="font-family:inherit;word-break:break-word;white-space:pre-wrap;margin:0">${email.text}</pre>`;
    setTimeout(() => {
      editorRef.current?.focus();
      setForm((f) => ({ ...f, content: body, text: email.text || '' }));
    }, 0);
  }

  function openDraft(draft: any) {
    setForm({
      ...initialForm,
      ...draft,
      includeSignature: draft.includeSignature ?? true,
      draftId: draft.draftId,
    });
    setTimeout(() => editorRef.current?.focus());
  }

  function resetForm() {
    setForm({ ...initialForm });
    editorRef.current?.clearEditor();
  }

  function formatImage(content: string) {
    content = content || '';
    const domain = settings?.r2Domain as string | undefined;
    return content.replace(/{{domain}}/g, toOssDomain(domain) + '/');
  }

  function pushRecipient() {
    const raw = recipientInput.trim();
    if (!raw) return;
    raw.split(/[,，]/).map((s) => s.trim()).filter(Boolean).forEach((email) => {
      if (isEmail(email) && !form.receiveEmail.includes(email)) {
        setForm((f) => ({ ...f, receiveEmail: [...f.receiveEmail, email] }));
      }
    });
    setRecipientInput('');
  }

  function removeRecipient(email: string) {
    setForm((f) => ({ ...f, receiveEmail: f.receiveEmail.filter((e) => e !== email) }));
  }

  const filteredSuggestions = recipientInput
    ? writerStore.sendRecipientRecord
        .filter((r) => r.email.startsWith(recipientInput) && !form.receiveEmail.includes(r.email))
        .slice(0, 10)
    : [];

  async function chooseFile() {
    const input = document.createElement('input');
    input.type = 'file';
    input.multiple = true;
    input.click();
    input.onchange = async (e: any) => {
      const files = e.target.files as FileList;
      if (!files) return;
      const currentTotal = form.attachments.reduce((sum, a) => sum + (a.size || 0), 0);
      let runningTotal = currentTotal;
      let rejected = 0;
      for (const file of Array.from(files)) {
        if (file.size > MAX_ATTACHMENT_SIZE) {
          rejected += 1;
          continue;
        }
        if (runningTotal + file.size > MAX_TOTAL_ATTACHMENT_SIZE) {
          rejected += 1;
          continue;
        }
        const content = await fileToBase64(file);
        runningTotal += file.size;
        setForm((f) => ({
          ...f,
          attachments: [...f.attachments, { filename: file.name, size: file.size, content, contentType: file.type }],
        }));
      }
      if (rejected > 0) {
        toast.warning(t('attachmentTooLarge', { count: rejected }));
      }
    };
  }

  function delAtt(idx: number) {
    setForm((f) => ({ ...f, attachments: f.attachments.filter((_, i) => i !== idx) }));
  }

  async function sendEmail() {
    if (form.receiveEmail.length === 0) {
      toast.error(t('emptyRecipientMsg'));
      return;
    }
    if (!form.subject) {
      toast.error(t('emptySubjectMsg'));
      return;
    }
    const content = editorRef.current?.getContent() || form.content;
    const text = editorRef.current?.getText() || form.text;
    if (!content) {
      toast.error(t('emptyContentMsg'));
      return;
    }

    const fd = new FormData();
    fd.append('sendEmail', form.sendEmail);
    fd.append('receiveEmail', JSON.stringify(form.receiveEmail.map((address) => ({ address, name: '' }))));
    fd.append('accountId', String(form.accountId));
    fd.append('name', form.name);
    fd.append('subject', form.subject);
    fd.append('content', content);
    fd.append('text', text);
    fd.append('sendType', form.sendType);
    fd.append('emailId', String(form.emailId));
    form.attachments.forEach((att, i) => {
      fd.append(`attachments[${i}]`, att.content);
      fd.append(`attachmentFilenames[${i}]`, att.filename);
      fd.append(`attachmentSizes[${i}]`, String(att.size));
      fd.append(`attachmentContentTypes[${i}]`, att.contentType);
    });

    const toastId = toast.loading(<SendPercent value={percent} desc={t('sending')} />, {
      duration: Infinity,
    });

    try {
      const result = (await emailSend(fd, (e) =>
        setPercent(Math.round((e.loaded * 98) / (e.total ?? 1))),
      )) as any[];
      const first = result[0];
      result.forEach((item: any) => {
        emailStore.sendScroll?.addItem(item);
      });
      toast.dismiss(toastId);
      toast.success(first?.subject ?? t('sendSuccessMsg'));

      await refreshUserInfo();
      addRecipientRecord();
      if (form.draftId) {
        const db = getDB();
        await db.draft.delete(form.draftId);
        await db.att.delete(form.draftId);
        useDraftStore.setState((s) => ({ refreshList: s.refreshList + 1 }));
      }
      closeWriter();
      resetForm();
    } catch (e: any) {
      toast.dismiss(toastId);
      toast.error(e?.message || t('sendFailMsg'));
      if (e?.code === 401) {
        setToken('');
        window.location.href = '/login';
      }
    } finally {
      setPercent(0);
    }
  }

  function addRecipientRecord() {
    const oldWithoutCurrent = writerStore.sendRecipientRecord.filter(
      (r) => !form.receiveEmail.includes(r.email),
    );
    const next = [...form.receiveEmail.map((email) => ({ email })), ...oldWithoutCurrent].slice(0, 500);
    writerStore.setSendRecipientRecord(next);
  }

  async function close() {
    const content = editorRef.current?.getContent() ?? form.content;
    if (form.draftId) {
      setDraftInStore({ ...form, content });
      closeWriter();
      resetForm();
      return;
    }
    if (!content && !form.subject && form.receiveEmail.length === 0) {
      closeWriter();
      resetForm();
      return;
    }
    setConfirmClose(true);
  }

  async function saveDraftAndClose() {
    const content = editorRef.current?.getContent() ?? form.content;
    const db = getDB();
    const draftId = await db.draft.add({
      subject: form.subject,
      toEmail: form.receiveEmail.join(','),
      content,
      createTime: Date.now(),
      accountId: form.accountId,
    } as DraftRecord);
    await db.att.put({ draftId, atts: form.attachments as any });
    useDraftStore.setState((s) => ({ refreshList: s.refreshList + 1 }));
    closeWriter();
    resetForm();
  }

  function discardDraft() {
    closeWriter();
    resetForm();
  }

  async function refreshPreviewSignature() {
    const req = ++previewReqRef.current;
    setPreviewSignature('');
    if (form.includeSignature && form.sendEmail) {
      try {
        const signature: any = await signatureGet(form.sendEmail);
        if (req !== previewReqRef.current) return;
        setPreviewSignature(signature.content || '');
      } catch {
        if (req !== previewReqRef.current) return;
        setPreviewSignature('');
      }
    }
  }

  useEffect(() => {
    if (previewOpen) refreshPreviewSignature();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [previewOpen, form.includeSignature, form.sendEmail, signatureStore.refresh]);

  const previewHtml = () => {
    const sig = form.includeSignature && previewSignature
      ? `<div style="margin-top:16px;">${previewSignature}</div>`
      : '';
    return formatImage(`${editorRef.current?.getContent() || form.content || ''}${sig}`);
  };

  return (
    <>
      <Sheet open={writerShow} onOpenChange={(o) => (o ? null : close())}>
        <SheetContent
          side="right"
          className="flex h-full w-full flex-col gap-3 overflow-y-auto bg-background p-5 sm:max-w-[720px]"
        >
          <SheetHeader className="mb-1 flex flex-row items-center justify-between">
            <div className="flex items-center gap-2">
              <Icon icon="hugeicons:quill-write-01" width="28" height="28" />
              <span className="text-sm text-muted-foreground">{t('sender')}:</span>
              <span className="font-bold">{form.name}</span>
              <span className="text-muted-foreground">&lt;{form.sendEmail}&gt;</span>
            </div>
            <Icon
              icon="material-symbols-light:close-rounded"
              width="22"
              height="22"
              className="cursor-pointer"
              onClick={close}
            />
          </SheetHeader>
          <SheetTitle className="hidden">{t('write')}</SheetTitle>

          <div className="flex flex-col gap-3">
            <div className="relative flex flex-wrap items-center gap-1 rounded-md border border-input bg-background p-2">
              <span className="px-2 text-sm text-muted-foreground">{t('recipient')}</span>
              {form.receiveEmail.map((email) => (
                <Badge key={email} variant="secondary" className="gap-1">
                  {email}
                  <Icon
                    icon="material-symbols-light:close-rounded"
                    width="14"
                    height="14"
                    className="cursor-pointer"
                    onClick={() => removeRecipient(email)}
                  />
                </Badge>
              ))}
              <input
                ref={recipientInputRef}
                className="min-w-[120px] flex-1 bg-transparent outline-none"
                value={recipientInput}
                onChange={(e) => {
                  setRecipientInput(e.target.value);
                  setDropdownOpen(true);
                }}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ',' || e.key === '，') {
                    e.preventDefault();
                    pushRecipient();
                  }
                  if (e.key === 'Backspace' && !recipientInput && form.receiveEmail.length > 0) {
                    removeRecipient(form.receiveEmail[form.receiveEmail.length - 1]);
                  }
                }}
                onBlur={() => setTimeout(() => setDropdownOpen(false), 200)}
              />
              {dropdownOpen && filteredSuggestions.length > 0 && (
                <div className="absolute left-0 top-full z-10 mt-1 max-h-60 w-full overflow-auto rounded-md border border-border bg-popover text-popover-foreground shadow">
                  {filteredSuggestions.map((s, i) => (
                    <div
                      key={`${s.email}-${i}`}
                      className="cursor-pointer px-3 py-1.5 text-sm hover:bg-accent"
                      onClick={() => {
                        setForm((f) => ({ ...f, receiveEmail: [...f.receiveEmail, s.email] }));
                        setRecipientInput('');
                      }}
                    >
                      {s.email}
                    </div>
                  ))}
                </div>
              )}
            </div>
            <Input
              value={form.subject}
              onChange={(e) => setForm((f) => ({ ...f, subject: e.target.value }))}
              placeholder={t('subject')}
            />
            <HtmlEditor
              ref={editorRef}
              placeholder={t('writeContent')}
              defaultValue={form.content}
              onChange={(content, text) => setForm((f) => ({ ...f, content, text }))}
            />
            <div className="flex flex-wrap items-center gap-3">
              <Icon icon="iconamoon:attachment-fill" width="24" height="24" className="cursor-pointer" onClick={chooseFile} />
              <Icon icon="icon-park-outline:clear-format" width="24" height="24" className="cursor-pointer" onClick={resetForm} />
              <label className="flex items-center gap-2 whitespace-nowrap text-sm">
                <Checkbox
                  checked={form.includeSignature}
                  onCheckedChange={(v) => setForm((f) => ({ ...f, includeSignature: v === true }))}
                />
                {t('includeSignature')}
              </label>
              <div className="flex max-h-28 flex-1 flex-wrap gap-1 overflow-y-auto">
                {form.attachments.map((att, i) => (
                  <div
                    key={i}
                    className="grid h-8 grid-cols-[auto_1fr_auto_auto] items-center gap-1 rounded bg-muted px-1.5 py-1 text-sm"
                  >
                    <Icon {...(getIconByName(att.filename) as any)} width={20} height={20} />
                    <span className="max-w-[140px] truncate">{att.filename}</span>
                    <span className="text-xs text-muted-foreground">{formatBytes(att.size)}</span>
                    <Icon
                      icon="material-symbols-light:close-rounded"
                      width="18"
                      height="18"
                      className="cursor-pointer"
                      onClick={() => delAtt(i)}
                    />
                  </div>
                ))}
              </div>
              <div className="ml-auto flex gap-2 whitespace-nowrap">
                <Button variant="outline" onClick={() => setPreviewOpen(true)}>
                  {t('preview')}
                </Button>
                {hasPerm('email:send') && (
                  <Button onClick={sendEmail}>
                    {form.sendType === 'reply'
                      ? t('reply')
                      : form.sendType === 'forward'
                      ? t('forward')
                      : t('send')}
                  </Button>
                )}
              </div>
            </div>
          </div>
        </SheetContent>
      </Sheet>

      <AlertDialog open={confirmClose} onOpenChange={setConfirmClose}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('saveDraftConfirm')}</AlertDialogTitle>
            <AlertDialogDescription>{t('saveDraftConfirmDesc')}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={discardDraft}>{t('discard')}</AlertDialogCancel>
            <AlertDialogAction onClick={saveDraftAndClose}>{t('save')}</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <Sheet open={previewOpen} onOpenChange={setPreviewOpen}>
        <SheetContent side="right" className="w-full sm:max-w-[860px]">
          <SheetHeader>
            <SheetTitle>{t('signaturePreview')}</SheetTitle>
          </SheetHeader>
          <div className="m-3 h-[calc(82vh-120px)] overflow-auto rounded-md border border-border p-3">
            <ShadowHtml html={previewHtml()} />
          </div>
        </SheetContent>
      </Sheet>
    </>
  );
}
