// mail-vue/src/views/email/index.vue
<template>
  <div class="email-view">
    <MobileAccountSelector />
    <emailScroll ref="scroll"
                 :cancel-success="cancelStar"
                 :star-success="addStar"
                 :getEmailList="getEmailList"
                 :emailDelete="emailDelete"
                 :star-add="starAdd"
                 :star-cancel="starCancel"
                 :time-sort="params.timeSort"
                 :email-read="emailRead"
                 :show-unread="true"
                 actionLeft="4px"
                 @jump="jumpContent"
    >
      <template #first>
        <Icon class="icon" @click="changeTimeSort" icon="material-symbols-light:timer-arrow-down-outline"
              v-if="params.timeSort === 0" width="28" height="28"/>
        <Icon class="icon" @click="changeTimeSort" icon="material-symbols-light:timer-arrow-up-outline" v-else
              width="28" height="28"/>
      </template>

    </emailScroll>
  </div>
</template>

<script setup>
import {useAccountStore} from "@/store/account.js";
import {useEmailStore} from "@/store/email.js";
import {useSettingStore} from "@/store/setting.js";
import emailScroll from "@/components/email-scroll/index.vue"
import MobileAccountSelector from "@/components/mobile-account-selector/index.vue"
import {emailList, emailDelete, emailLatest, emailRead} from "@/request/email.js";
import {starAdd, starCancel} from "@/request/star.js";
import {defineOptions, h, onMounted, reactive, ref, watch} from "vue";
import {sleep} from "@/utils/time-utils.js";
import router from "@/router/index.js";
import {Icon} from "@iconify/vue";
import { useRoute } from 'vue-router'

defineOptions({
  name: 'email'
})

const route = useRoute();
const emailStore = useEmailStore();
const accountStore = useAccountStore();
const settingStore = useSettingStore();
const scroll = ref({})
const params = reactive({
  timeSort: 0,
})

onMounted(() => {
  emailStore.emailScroll = scroll;
  latest()
})


watch(() => accountStore.currentAccountId, () => {
  scroll.value.refreshList();
})

function changeTimeSort() {
  params.timeSort = params.timeSort ? 0 : 1
  scroll.value.refreshList();
}

function jumpContent(email) {
  emailStore.contentData.email = email
  emailStore.contentData.delType = 'logic'
  emailStore.contentData.showUnread = true
  emailStore.contentData.showStar = true
  emailStore.contentData.showReply = true
  router.push('/message')
}

const existIds = new Set();

async function latest() {
  while (true) {

    let autoRefresh = settingStore.settings.autoRefresh;
    await sleep(autoRefresh > 1 ? autoRefresh * 1000 : 3000);

    if (route.name !== 'email') {
      continue;
    }

    const latestId = scroll.value.latestEmail?.emailId

    if (!scroll.value.firstLoad && autoRefresh > 1) {
      try {
        const accountId = accountStore.currentAccountId
        const allReceive = scroll.value.latestEmail?.allReceive
        const curTimeSort = params.timeSort
        let list = []

        //确保发起请求时最后一个邮件是当前账号的,或者
        if (accountId === scroll.value.latestEmail?.reqAccountId) {
          list = await emailLatest(latestId, accountId, allReceive);
        }

        //确保请求回来后，账号没有切换，时间排序没有改变，全部邮件类型没变
        if (accountId === accountStore.currentAccountId && params.timeSort === curTimeSort && allReceive === accountStore.currentAccount.allReceive) {
          if (list.length > 0) {

            for (let email of list) {

              email.reqAccountId = accountId;
              email.allReceive = allReceive;

              if (!existIds.has(email.emailId)) {

                existIds.add(email.emailId)
                scroll.value.addItem(email)

                await sleep(50)
              }

            }

          }

        }
      } catch (e) {
        if (e.code === 401 || e.code === 403) {
          settingStore.settings.autoRefresh = 0;
        }
        console.error(e)
      }
    }
  }
}

function addStar(email) {
  emailStore.starScroll?.addItem(email)
}

function cancelStar(email) {
  emailStore.starScroll?.deleteEmail([email.emailId])
}

function getEmailList(emailId, size) {
  const accountId =  accountStore.currentAccountId;
  const allReceive = accountStore.currentAccount.allReceive;
  return emailList(accountId, allReceive, emailId, params.timeSort, size, 0).then(data => {
    data.latestEmail.reqAccountId = accountId;
    data.latestEmail.allReceive = allReceive;
    return data;
  })
}

</script>
<style scoped>
.email-view {
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.email-view :deep(.email-container) {
  flex: 1;
  min-height: 0;
}
</style>

<style>
.icon {
  cursor: pointer;
}
</style>

// mail-react/src/views/email/index.tsx
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Icon } from '@iconify/react';
import EmailScroll, { type EmailScrollHandle } from '@/components/email-scroll';
import MobileAccountSelector from '@/components/mobile-account-selector';
import {
  emailList,
  emailRead,
  emailDelete as emailDeleteFn,
  emailLatest,
} from '@/request/email';
import { starAdd as starAddFn, starCancel as starCancelFn } from '@/request/star';
import { useAccountStore } from '@/store/account';
import { useEmailStore } from '@/store/email';
import { useSettingStore } from '@/store/setting';
import { sleep } from '@/utils/time-utils';

export default function EmailView() {
  const navigate = useNavigate();
  const { t } = useTranslation();
  const accountId = useAccountStore((s) => s.currentAccountId);
  const account = useAccountStore();
  const emailStore = useEmailStore();
  const settingStore = useSettingStore();
  const scrollRef = useRef<EmailScrollHandle>(null);
  const [timeSort, setTimeSort] = useState(0);
  const existIdsRef = useRef<Set<number>>(new Set());
  const timeSortRef = useRef(timeSort);
  timeSortRef.current = timeSort;

  useEffect(() => {
    let cancelled = false;
    const onVisibility = () => {
      // resume immediately when the tab becomes visible — the loop's await below
      // wakes up on its own once `document.hidden` flips.
    };

    async function latestLoop() {
      while (!cancelled) {
        const autoRefresh: number = (settingStore.settings as any)?.autoRefresh ?? 0;
        await sleep(autoRefresh > 1 ? autoRefresh * 1000 : 3000);
        if (cancelled) return;
        if (document.hidden) {
          // Tab backgrounded: wait for visibility before burning bandwidth.
          await new Promise<void>((resolve) => {
            const handler = () => {
              if (!document.hidden) {
                document.removeEventListener('visibilitychange', handler);
                resolve();
              }
            };
            document.addEventListener('visibilitychange', handler);
          });
          if (cancelled) return;
        }

        const handle = scrollRef.current;
        if (!handle || handle.firstLoad) continue;
        if (autoRefresh <= 1) continue;

        const latestEmail = handle.latestEmail;
        const latestId = latestEmail?.emailId;
        if (!latestId) continue;

        try {
          const curAccountId = useAccountStore.getState().currentAccountId;
          const allReceive = latestEmail?.allReceive;
          const curTimeSort = timeSortRef.current;
          let list: any[] = [];
          if (curAccountId === latestEmail?.reqAccountId) {
            list = await emailLatest(latestId, curAccountId, allReceive);
          }
          if (cancelled) return;
          if (
            curAccountId === useAccountStore.getState().currentAccountId &&
            timeSortRef.current === curTimeSort &&
            allReceive === useAccountStore.getState().currentAccount?.allReceive
          ) {
            for (const email of list) {
              if (cancelled) return;
              email.reqAccountId = curAccountId;
              email.allReceive = allReceive;
              // existIdsRef is the source of truth: skipping via the ref guards
              // both the first-emit race and any re-emit after a stale response.
              if (existIdsRef.current.has(email.emailId)) continue;
              existIdsRef.current.add(email.emailId);
              handle.addItem(email);
            }
          }
        } catch (e: any) {
          if (e?.code === 401 || e?.code === 403) {
            settingStore.settings.autoRefresh = 0;
          }
        }
      }
    }

    void latestLoop();
    document.addEventListener('visibilitychange', onVisibility);
    return () => {
      cancelled = true;
      document.removeEventListener('visibilitychange', onVisibility);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!accountId) return;
    existIdsRef.current = new Set();
    scrollRef.current?.refreshList();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accountId]);

  function changeTimeSort() {
    setTimeSort((cur) => {
      const next = cur ? 0 : 1;
      scrollRef.current?.refreshList();
      return next;
    });
  }

  function jumpContent(email: any) {
    emailStore.setContentData({
      email,
      delType: 'logic',
      showUnread: true,
      showStar: true,
      showReply: true,
    });
    navigate('/message');
  }

  function addStar(email: any) {
    const starScroll = useEmailStore.getState().starScroll;
    starScroll?.addItem(email);
  }

  function cancelStar(email: any) {
    const starScroll = useEmailStore.getState().starScroll;
    starScroll?.deleteEmail([email.emailId]);
    toast(t('undoRemoveStar'), {
      action: {
        label: t('undo'),
        onClick: () => {
          starScroll?.addItem(email);
        },
      },
      duration: 5000,
    });
  }

  async function getEmailList(emailId: number, size: number) {
    const allReceive = account.currentAccount?.allReceive ?? 0;
    const data = await emailList(accountId, allReceive, emailId, timeSortRef.current, size, 0);
    if (data.latestEmail) {
      data.latestEmail.reqAccountId = accountId;
      data.latestEmail.allReceive = allReceive;
    }
    return data;
  }

  return (
    <div className="grid h-full grid-rows-[auto_1fr] overflow-hidden">
      <MobileAccountSelector />
      <EmailScroll
        ref={scrollRef}
        getEmailList={getEmailList}
        emailDelete={emailDeleteFn}
        emailRead={emailRead}
        starAdd={starAddFn}
        starCancel={starCancelFn}
        timeSort={timeSort}
        showUnread
        showStatus={false}
        showAccountIcon
        showUserInfo={false}
        showStar
        allowStar
        actionLeft="4px"
        onJump={jumpContent}
        starSuccess={addStar}
        cancelSuccess={cancelStar}
        headerFirstSlot={
          <Icon
            className="cursor-pointer"
            icon={
              timeSort === 0
                ? 'material-symbols-light:timer-arrow-down-outline'
                : 'material-symbols-light:timer-arrow-up-outline'
            }
            width="28"
            height="28"
            onClick={changeTimeSort}
          />
        }
      />
    </div>
  );
}
